In [35]:
!pip install -U langchain-ollama langchain-openai

Requirement already satisfied: langchain-ollama in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: langchain-openai in /usr/local/lib/python3.12/dist-packages (1.0.2)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-ollama) (1.0.3)
Requirement already satisfied: ollama<1.0.0,>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from langchain-ollama) (0.6.0)
Requirement already satisfied: openai<3.0.0,>=1.109.1 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (1.109.1)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (0.12.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.4.38)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (25.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.11.10)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (8.5.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (4.15.0)
Requirement already satisfied: httpx>=0.27 in /usr/local/lib/python3.12/dist-packages (from ollama<1.0.0,>=0.6.0->langchain-ollama) (0.28.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (4.11.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (0.11.1)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (4.67.1)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2024.11.6)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2.32.4)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai<3.0.0,>=1.109.1->langchain-openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.11.4)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken<1.0.0,>=0.7.0->langchain-openai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken<1.0.0,>=0.7.0->langchain-openai) (2.5.0)

In [36]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [37]:
!ls /content/drive/MyDrive/review_dataset

w_review_train.csv  w_review_train.parquet

In [38]:
import duckdb

con = duckdb.connect(database=':memory:', read_only=False)

In [39]:
df = con.execute("SELECT * FROM read_csv_auto('/content/drive/MyDrive/review_dataset/w_review_train.csv', parallel=false, encoding='UTF-8', ignore_errors=true)").fetchdf()

df.head()

                                             column0  column1
0  ร้านอาหารใหญ่มากกกกกกก \nเลี้ยวเข้ามาเจอห้องน้...        3
1  อาหารที่นี่เป็นอาหารจีนแคะที่หากินยากในบ้านเรา...        4
2  ปอเปี๊ยะสด ทุกวันนี้รู้สึกว่าหากินยาก (ร้านที่...        3
3  รัานคัพเค้กในเมืองไทยมีไม่มาก หลายๆคนอาจจะสงสั...        5
4  อร่อย!!! เดินผ่านDigital gatewayทุกวัน ไม่ยักร...        5

In [40]:
df.shape

(40000, 2)

In [41]:
con.execute("COPY df TO '/content/drive/MyDrive/review_dataset/w_review_train.parquet' (FORMAT PARQUET)")

In [42]:
parquet_avg_rating_direct = con.execute("SELECT AVG(column1) FROM '/content/drive/MyDrive/review_dataset/w_review_train.parquet' WHERE column0 LIKE '%อร่อย%'").fetchone()[0]
parquet_avg_rating_direct

3.8313027179006562

In [43]:
parquet_file_path = '/content/drive/MyDrive/review_dataset/w_review_train.parquet'

In [44]:
parquet_avg_rating_direct = con.execute(f"SELECT AVG(column1) FROM '{parquet_file_path}' WHERE column0 LIKE '%อร่อย%'").fetchone()[0]
parquet_avg_rating_direct

3.8313027179006562

In [45]:
coffee_keywords = [
    'กาแฟ', 'คาเฟ่', 'coffee', 'cafe', 'เอสเปรสโซ่', 'ลาเต้',
    'มอคค่า', 'คาปูชิโน่', 'เฟรนช์เพรส', 'cold brew', 'drip',
    'espresso', 'latte', 'americano', 'macchiato', 'brew',
    'specialty', 'slow bar', 'ร้านกาแฟ', 'ร้านคาเฟ่', 'กาแฟสด',
    'เมนูกาแฟ', 'กาแฟนม', 'กาแฟดำ', 'ร้านบาริสต้า', 'barista', 'coffee shop'
]

where_clause = " OR ".join([f"column0 LIKE '%{keyword}%'" for keyword in coffee_keywords])

In [46]:
%%time
coffee_reviews_df = con.execute(f"SELECT * FROM '{parquet_file_path}' WHERE {where_clause}").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

CPU times: user 4.55 s, sys: 32.2 ms, total: 4.59 s
Wall time: 5.06 s

In [47]:
csv_file_path = '/content/drive/MyDrive/review_dataset/w_review_train.csv'

In [48]:
%%time
coffee_reviews_df_csv = con.execute(f"SELECT * FROM read_csv_auto('{csv_file_path}', parallel=false, encoding='UTF-8', ignore_errors=true) WHERE {where_clause}").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

CPU times: user 2.66 s, sys: 50.1 ms, total: 2.71 s
Wall time: 5.88 s

In [49]:
coffee_reviews_df.head()

                                             column0  column1
0  ร้านอาหารใหญ่มากกกกกกก \nเลี้ยวเข้ามาเจอห้องน้...        3
1  วันนี้ได้มีโอกาสไปนั่งซดกาแฟที่ร้านวาวี แถวๆอา...        4
2  สารภาพว่าไม่เคยคิดจะไปต่อคิวซื้อมากินเองครับ บ...        3
3  ร้านอาหารญี่ปุ่นร้านนี้ ใจจริงไม่อยากแนะนำเลยค...        5
4  เดือนแรกที่เค้าต่อคิวกัน 2 - 3 ชั่วโมง เราก็ว่...        5

In [50]:
coffee_reviews_df.shape

(4981, 2)

In [51]:
!curl -fsSL https://ollama.com/install.sh | sh

>>> Cleaning up old version at /usr/local/lib/ollama
>>> Installing ollama to /usr/local
>>> Downloading Linux amd64 bundle
######################################################################## 100.0%
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: systemd is not running
WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.

In [52]:
!nohup ollama serve &

nohup: appending output to 'nohup.out'

In [53]:
!ollama pull gemma3:270m

In [54]:
!ollama list

NAME           ID              SIZE      MODIFIED
gemma3:270m    e7d36fb2c3b3    291 MB    Less than a second ago

In [55]:
!ollama run gemma3:270m "สวัสดี"

สวัสดีค่ะ ยินดีที่ได้รู้จักนะคะ 😊

In [56]:
!curl -s http://127.0.0.1:11434/api/tags

{"models":[{"name":"gemma3:270m","model":"gemma3:270m","modified_at":"2025-11-04T06:43:52.561363164Z","size":291554930,"digest":"e7d36fb2c3b3293cfe56d55889867a064b3a2b22e98335f2e6e8a387e081d6be","details":{"parent_model":"","format":"gguf","family":"gemma3","families":["gemma3"],"parameter_size":"268.10M","quantization_level":"Q8_0"}}]}

In [57]:
from langchain_ollama import ChatOllama
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

In [58]:
llm = ChatOllama(model="gemma3:270m")

In [59]:
response = llm.invoke("สวัสดี")
print(response)

content='สวัสดีค่ะ ยินดีที่ได้รู้จักนะคะ 😊\n' additional_kwargs={} response_metadata={'model': 'gemma3:270m', 'created_at': '2025-11-04T06:43:54.23003325Z', 'done': True, 'done_reason': 'stop', 'total_duration': 331313230, 'load_duration': 202986951, 'prompt_eval_count': 10, 'prompt_eval_duration': 8959151, 'eval_count': 12, 'eval_duration': 90811484, 'model_name': 'gemma3:270m', 'model_provider': 'ollama'} id='lc_run--79a79a66-be04-42f2-a589-56d5980c79a1-0' usage_metadata={'input_tokens': 10, 'output_tokens': 12, 'total_tokens': 22}

In [60]:
template = """
คุณเป็นครูสอน Python
คำถาม : {question}
"""

In [61]:
prompt = PromptTemplate(
    input_variables=["question"],
    template=template
)

In [62]:
formatted_prompt = prompt.format(question="เขียนโค้ดหาผลรวมของตัวเลข 1 ถึง 10")
print(formatted_prompt)

คุณเป็นครูสอน Python
คำถาม : เขียนโค้ดหาผลรวมของตัวเลข 1 ถึง 10

In [63]:
chain = prompt | llm

In [64]:
response = chain.invoke({"question": "เขียนโค้ดหาผลรวมของตัวเลข 1 ถึง 10"})
response

AIMessage(content='```python\ndef find_sum(numbers):\n    """\n    หาผลรวมของตัวเลข 1 ถึง 10\n    """\n    total = 0\n    for number in numbers:\n        total += number\n    return total\n\n# ตัวอย่างการใช้งาน\nnumbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\nresult = find_sum(numbers)\nprint(result)\n```\n\n**คำอธิบายโค้ด:**\n\n1. **`def find_sum(numbers):`**:  กำหนดชื่อ funzione `find_sum` ที่จะเรียกใช้ ซึ่งจะถูกเรียกโดยใช้เมื่อมีการเรียกใช้งานโปรแกรม\n2. **`total = 0`**:  สร้างค่า `total` ที่จะเก็บผลรวมของตัวเลข\n3. **`for number in numbers:`**:  ใช้ `for` loop เพื่อวนซ้ำผ่านแต่ละตัวเลขใน `numbers`\n4. **`total += number`**:  เพิ่มค่า `number` เข้าไปใน `total`\n5. **`return total`**:  คืนค่า `total`\n6. **`numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`**:  สร้าง list ของตัวเลขที่ต้องการหาผลรวม\n7. **`result = find_sum(numbers)`**:  เรียกใช้ function `find_sum` เพื่อหาผลรวม\n8. **`print(result)`**:  แสดงผลลัพธ์ที่ได้จาก fungsi\n**ตัวอย่างการใช้งาน:**\n\n```python\nnumbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\nresult = find_sum(numbers)\nprint(result)\n```\n\n**Output:**\n\n```\n15\n```\n\n**ข้อดีของโค้ดนี้:**\n\n* **ใช้งานง่าย:**  โค้ดนี้เป็นโค้ดที่เข้าใจง่ายและใช้งานได้ง่าย\n* **อ่านง่าย:**  โค้ดนี้มีโครงสร้างที่ชัดเจน\n* **สามารถปรับปรุงได้:**  โค้ดนี้สามารถปรับปรุงได้โดยเพิ่มฟังก์ชันเพิ่มเติมเพื่อจัดการกับตัวอย่างที่กำหนดได้\n* **สามารถอัปเดต:**  สามารถอัปเดตโค้ดได้โดยการเพิ่มฟังก์ชันเพิ่มเติมที่เกี่ยวข้องกับตัวเลขที่ต้องการ\n\n**ข้อควรระวัง:**\n\n* **ความปลอดภัย:**  ในบางกรณี คุณอาจพิจารณاةความปลอดภัยของโปรแกรมที่เขียนด้วย Python หากมีการใช้ข้อมูลที่อาจถูกรบกวน\n* **การจัดการตัวแปร:**  ควรใช้ตัวแปรเพื่อจัดการตัวเลขที่ต้องการหาผลรวม\n* **การใช้ `try...except`:**  หากตัวเลขที่ต้องการหาผลรวมไม่สามารถเขียนได้ในตัวแปร โปรดใช้ `try...except` เพื่อจัดการกับกรณีที่ตัวเลขไม่สามารถเขียนได้\n\n', additional_kwargs={}, response_metadata={'model': 'gemma3:270m', 'created_at': '2025-11-04T06:43:58.603006613Z', 'done': True, 'done_reason': 'stop', 'total_duration': 4329037120, 'load_duration': 170501031, 'prompt_eval_count': 37, 'prompt_eval_duration': 14491808, 'eval_count': 643, 'eval_duration': 3121753591, 'model_name': 'gemma3:270m', 'model_provider': 'ollama'}, id='lc_run--85cfa0f3-384a-4899-ae47-415b66509b46-0', usage_metadata={'input_tokens': 37, 'output_tokens': 643, 'total_tokens': 680})

In [65]:
from IPython.display import display, Markdown

In [67]:
display(Markdown(response.content))

```python
def find_sum(numbers):
    """
    หาผลรวมของตัวเลข 1 ถึง 10
    """
    total = 0
    for number in numbers:
        total += number
    return total

# ตัวอย่างการใช้งาน
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
result = find_sum(numbers)
print(result)
```

**คำอธิบายโค้ด:**

1. **`def find_sum(numbers):`**:  กำหนดชื่อ funzione `find_sum` ที่จะเรียกใช้ ซึ่งจะถูกเรียกโดยใช้เมื่อมีการเรียกใช้งานโปรแกรม
2. **`total = 0`**:  สร้างค่า `total` ที่จะเก็บผลรวมของตัวเลข
3. **`for number in numbers:`**:  ใช้ `for` loop เพื่อวนซ้ำผ่านแต่ละตัวเลขใน `numbers`
4. **`total += number`**:  เพิ่มค่า `number` เข้าไปใน `total`
5. **`return total`**:  คืนค่า `total`
6. **`numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`**:  สร้าง list ของตัวเลขที่ต้องการหาผลรวม
7. **`result = find_sum(numbers)`**:  เรียกใช้ function `find_sum` เพื่อหาผลรวม
8. **`print(result)`**:  แสดงผลลัพธ์ที่ได้จาก fungsi
**ตัวอย่างการใช้งาน:**

```python
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
result = find_sum(numbers)
print(result)
```

**Output:**

```
15
```

**ข้อดีของโค้ดนี้:**

* **ใช้งานง่าย:**  โค้ดนี้เป็นโค้ดที่เข้าใจง่ายและใช้งานได้ง่าย
* **อ่านง่าย:**  โค้ดนี้มีโครงสร้างที่ชัดเจน
* **สามารถปรับปรุงได้:**  โค้ดนี้สามารถปรับปรุงได้โดยเพิ่มฟังก์ชันเพิ่มเติมเพื่อจัดการกับตัวอย่างที่กำหนดได้
* **สามารถอัปเดต:**  สามารถอัปเดตโค้ดได้โดยการเพิ่มฟังก์ชันเพิ่มเติมที่เกี่ยวข้องกับตัวเลขที่ต้องการ

**ข้อควรระวัง:**

* **ความปลอดภัย:**  ในบางกรณี คุณอาจพิจารณاةความปลอดภัยของโปรแกรมที่เขียนด้วย Python หากมีการใช้ข้อมูลที่อาจถูกรบกวน
* **การจัดการตัวแปร:**  ควรใช้ตัวแปรเพื่อจัดการตัวเลขที่ต้องการหาผลรวม
* **การใช้ `try...except`:**  หากตัวเลขที่ต้องการหาผลรวมไม่สามารถเขียนได้ในตัวแปร โปรดใช้ `try...except` เพื่อจัดการกับกรณีที่ตัวเลขไม่สามารถเขียนได้

In [68]:
prompt1 = PromptTemplate(
    template="แปลโจทย์เกี่ยวกับ {question}"
)

chain1 = prompt1 | llm
prompt2 = PromptTemplate(
    template="ทำความเข้าใจโจทย์ที่แปลแล้วต่อไปนี้ {translate}"
)

chain2 = prompt2 | llm
prompt3 = PromptTemplate(
    template="แก้โจทย์ตามที่เข้าใจต่อไปนี้ {understand}"
)

chain3 = prompt3 | llm
prompt4 = PromptTemplate(
    template="อธิบายวิธิีทำจากผลลัทธ์ต่อไปนี้ {solve}"
)

chain4 = prompt4 | llm

In [69]:
parser_chain = StrOutputParser()

full_chain = chain1 | chain2 | chain3 | chain4 | parser_chain

result = full_chain.invoke({"question":"2x + 5 = 15"})

result

'ถูกต้องแล้วครับ! การแปลโจทย์ที่ "2x + 5 = 15" เป็นความหมายถูกต้องและเป็นภาษาที่เข้าใจง่ายที่สุด โดยการใช้ผลลัทธ์ที่เน้นไปที่การ **จัดเรียงลำดับความสำคัญของคำต่างๆ ในโจทย์** เพื่อให้เข้าใจความหมายของคำแต่ละคำได้อย่างชัดเจน'

In [70]:
import os
from langchain_openai import ChatOpenAI

In [71]:
OPENAI_API_KEY = "xxx"

os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY

In [72]:
llm2 = ChatOpenAI(model="gpt-4o-mini")

In [73]:
chain1 = prompt1 | llm2
chain2 = prompt2 | llm2
chain3 = prompt3 | llm2
chain4 = prompt4 | llm2

full_chain = chain1 | chain2 | chain3 | chain4 | parser_chain

In [75]:
formatted_result = result.replace('\\[', '$$') \
                         .replace('\\]', '$$') \
                         .replace('\\(', '$') \
                         .replace('\\)', '$')
display(Markdown(formatted_result))

ถูกต้องแล้วครับ! การแปลโจทย์ที่ "2x + 5 = 15" เป็นความหมายถูกต้องและเป็นภาษาที่เข้าใจง่ายที่สุด โดยการใช้ผลลัทธ์ที่เน้นไปที่การ **จัดเรียงลำดับความสำคัญของคำต่างๆ ในโจทย์** เพื่อให้เข้าใจความหมายของคำแต่ละคำได้อย่างชัดเจน

In [76]:
prompt_template = """
[1. Role/Context บอก LLM ว่าควรทำตัวเป็นอะไร]
คุณเป็น AI ที่เชี่ยวชาญในการวิเคราะห์รีวิวภาษาไทย

[2. Task Description บอกงานที่ต้องทำ]
จาก Review ต่อไปนี้ ให้ Extract 3 keywords
ที่เป็นตัวแทนของ Review นี้ได้ดีที่สุด

[3. Input Data ข้อมูลที่ต้องประมวลผล]
Review: {review}

[4. Output Format บอกรูปแบบของคำตอบ]
ตอบในรูปแบบ JSON โดยมีคีย์เป็น 'keywords'
เช่น {{"keywords": "กาแฟ, บรรยากาศ, ราคา"}

[5. Constraints ข้อจำกัดหรือเงื่อนไข]
- ต้องเป็นคำภาษาไทย
- คั่นด้วย comma
- หากไม่พบให้ตอบ 'ไม่ระบุ'

[6. Examples (optional) ตัวอย่าง input/output]
ตัวอย่าง
Input: "กาแฟอร่อย บรรยากาศดี ราคาแพง"
Output: {"keywords": "กาแฟ, บรรยากาศ, ราคา"}
"""

In [77]:
prompt = """
Extract keywords from this review
{review}
"""

# Pros Simple, fast
# Cons อาจได้ผลไม่ดีกับ Tasks ซับซ้อน

In [78]:
prompt = """
Extract keywords from reviews.

Example 1
Review: "กาแฟอร่อย บริการดี"
Keywords: กาแฟ, บริการ

Example 2
Review: "ราคาแพง แต่คุ้มค่า"
Keywords: ราคา, คุณภาพ

Now extract from this review
Review: {review}
Keywords:
"""

# Pros ได้ผลดีกว่า Zero-shot
# Cons Prompt ใช้ Tokens มากขึ้น

In [79]:
prompt = """
Review: {review}

ขั้นตอนการ Extract keywords
1. อ่านรีวิวและเข้าใจความหมาย
2. ระบุหัวข้อหลักที่กล่าวถึง
3. เลือก 3 keywords ที่สำคัญที่สุด
4. ตอบในรูปแบบ JSON: {{"keywords": "คำ1, คำ2, คำ3"}}

ให้ทำทีละขั้นตอน
"""

# Pros ได้ผลดีกับ Reasoning tasks
# Cons ใช้ Tokens มากกว่า ช้ากว่า

In [80]:
keyword_prompt = PromptTemplate(
template = """
จาก Review ต่อไปนี้
Extract 3 keywords ที่เป็นตัวแทนของ Review นี้

Review: {review}

ขั้นตอนการ Extract keywords
1. อ่านรีวิวและเข้าใจความหมาย
2. ระบุหัวข้อหลักที่กล่าวถึง
3. เลือก 3 keywords ที่สำคัญที่สุด
4. ตอบในรูปแบบ JSON: {{"keywords": "คำ1, คำ2, คำ3"}}

ให้ทำทีละขั้นตอน
""")

In [81]:
sample_reviews = coffee_reviews_df['column0'].head(2)
sample_reviews

0    ร้านอาหารใหญ่มากกกกกกก \nเลี้ยวเข้ามาเจอห้องน้...
1    วันนี้ได้มีโอกาสไปนั่งซดกาแฟที่ร้านวาวี แถวๆอา...
Name: column0, dtype: object

In [82]:
sample_reviews.to_csv('/content/sample_reviews.csv', index=False)

In [83]:
keyword_extract = keyword_prompt | llm | StrOutputParser()

In [84]:
%%time
results = []
for review in sample_reviews:
    text = keyword_extract.invoke({"review": review})
    cleaned = (text).replace("**", "").strip()
    results.append({"review": review, "text": cleaned})

CPU times: user 124 ms, sys: 7.79 ms, total: 132 ms
Wall time: 3.53 s

In [87]:
for result in results:
    print(f"Review {result['review'][:1000]}...")
    print(f"text {result['text']}\n")

Review ร้านอาหารใหญ่มากกกกกกก
เลี้ยวเข้ามาเจอห้องน้ำก่อนเลย เออแปลกดี
ห้องทานหลักๆอยู่ชั้น 2 มีกาแฟ น้ำผึ้ง ซึ่งก็แค่เอาน้ำผึ้งมาราด แพงเวอร์ อย่าสั่งเลย
ลาบไข่ต้ม ไข่มันคาวอะ เลยไม่ประทับใจเท่าไหร่
ทอดมันหัวปลีกรอบอร่อยต้องเบิ้ล
พะแนงห่อไข่อร่อยดี เห้ยแต่ราคา 150บาทมันเกินไปนะ รับไม่ไหวว
เลิกกินแล้วมีขนมหวานให้กินฟรีเล็กน้อย )ขนมไทย)

คงไม่ไปซ้ำ แพงเกิน ...
text ```json
{"keywords": ["ร้านอาหาร", "ห้องน้ำ", "กาแฟ", "น้ำผึ้ง", "น้ำผึ้ง", "ลาบไข่ต้ม", "ไข่มัน", "ขนมไทย", "ขนมหวาน", "ฟรี", "ราคา", "แพง", "เกินไป", "รับไม่ไหว", "เลิกกิน", "ขนมหวาน", "ขนมไทย", "ร้านอาหาร", "อาหารใหญ่", "ราคาสูง", "ไม่ไปซ้ำ", "ราคาก็เกินไป", "รับไม่ไหว", "กินแล้วมีขนมหวานให้กินฟรี", "ขนมไทย", "ร้านอาหาร", "อาหาร", "อาหารใหญ่", "อาหารทะเล", "อาหารทะเลสดๆ", "ไข่ต้ม", "ไข่มัน", "น้ำผึ้ง", "น้ำผึ้งมาราด", "ไข่มันคาว", "ทำไมไม่ไปซ้ำ", "ราคาก็เกินไป", "ขั้นตอนการ Extract keywords": "1. อ่านรีวิวและเข้าใจความหมาย"
```

Review วันนี้ได้มีโอกาสไปนั่งซดกาแฟที่ร้านวาวี แถวๆอารีย์

ก็ได้ยินมาบ่อยๆละ จากหลายที่ แต่ที่บ่อยสุดก็จาก Twitter ว่ากาแฟที่นี่อร่อยมากกกกกกก
เรียกว่าระดับแฟนๆ Starbuck ยังต้องเหลียวมามอง ก็ดองมานานจนถึงวันนี้โอกาสเหมาะ ไป
present งานที่ตึก Software Park เสร็จก็เลยมาหาไรกินแถวนี้พอดี
จัดไป.....


บรรยากาศรอบๆร้านก็แต่งได้น่านั่ง อารมณ์ประมาณว่าอยู่ในสวนบ้านเราเอง ต้นไม้เยอะดี
อย่างน้อยก็เป็นสีเขียวเล็กๆ ในใจกลางเมืองได้ละ
เขียวชอุ่ม

ว่าแล้วไม่รอช้าขอ Test ไม่สิ Taste เลยดีกว่าเดินเข้าร้านทันใด ป้าบบ...

"พี่คับ เอา...ลาเต้ ร้อนแก้วนึงคับ"
ว่างๆ มานั่งจิบกาแฟ ฟังเพลง พักผ่อนได้ดีทีเดียว

จ่ายตังเสร็จ ก็ถูกพนักงานอัญเชิญไปรอที่โต๊ะ 55+ เพราะที่นี่เขาเสริฟให้ถึงที่ หุๆ
ก็เลือกที่นั่งริมกระจก จะได้เห็นสาวๆ เอ้ย วิวถนัดๆหน่อย
นั่งชมวิวรอกาแฟมา

ไม่นานเกินอึดใจ ไวไวยังไม่ทันสุก ลาเต้ร้อนๆก็มาวางอยู่ข้างหน้า
ซู้ดดดดดดด อ่าห์

ชำเลืองตามองลงไป....โอ้วว ที่นี่มีเล่นลายฟองนมด้วยเว้ยยย
แต่พอดีด้วยความตะกละไปนิดดันฉีกน้ำตาลเทใส่แล้วเผลอคน ก็เลยไม่ได้
ถ่ายรูปมาให้ดู 55+ เหลือแต่ซากอารยธรรมลาเต้เมพๆ


หน...
text ```json
{"keywords": ["กาแฟ", "ร้านวาวี", "อารีย์", "Starbuck", "แฟนๆ Starbuck", "กาแฟ", "ร้าน", "รีวิว", "ความอร่อย", "ราคา", "กินบ่อย", "จุกได้", "ซากอารยธรรมลาเต้", "เมพพพพ", "เมพพ", "เครื่องดื่ม", "รสชาติ", "กลิ่น", "รสชาติ", "มวยรุ่นเดียวกะ Starbuck", "ซัมซวย", "Omnia i900", "สีภาพถึงได้ไม่ค่อยสวยเท่าไหร", "ขั้นตอนการ Extract keywords"]
```

In [86]:
keyword_extract = keyword_prompt | llm2 | StrOutputParser()

In [89]:
for result in results:
    print(f"Review {result['review'][:100]}...")
    print(f"text {result['text']}\n")

In [90]:
!ollama pull scb10x/typhoon2.1-gemma3-4b

In [91]:
!ollama list

NAME                                  ID              SIZE      MODIFIED
scb10x/typhoon2.1-gemma3-4b:latest    8cfab9097c9d    2.6 GB    Less than a second ago
gemma3:270m                           e7d36fb2c3b3    291 MB    4 minutes ago

In [94]:
llm3 = ChatOllama(
    model="scb10x/typhoon2.1-gemma3-4b",
  )

In [95]:
keyword_extract = keyword_prompt | llm3 | StrOutputParser()

In [96]:
%%time
results = []
for review in sample_reviews:
    text = keyword_extract.invoke({"review": review})
    cleaned = (text).replace("**", "").strip()
    results.append({"review": review, "text": cleaned})

CPU times: user 231 ms, sys: 9.95 ms, total: 240 ms
Wall time: 18.4 s

In [97]:
for result in results:
    print(f"Review {result['review'][:100]}...")
    print(f"text {result['text']}\n")

Review ร้านอาหารใหญ่มากกกกกกก
เลี้ยวเข้ามาเจอห้องน้ำก่อนเลย เออแปลกดี
ห้องทานหลักๆอยู่ชั้น 2 มีกาแฟ น้ำผึ...
text แน่นอนครับ ผมจะช่วยคุณวิเคราะห์และดึงคำสำคัญจากรีวิวนี้ออกมาเป็น JSON ตามที่คุณต้องการ

ขั้นตอนที่ 1: อ่านรีวิวและเข้าใจความหมาย

รีวิวนี้พูดถึงร้านอาหารขนาดใหญ่ที่มีข้อดีและข้อเสียหลายอย่าง ได้แก่:

*   ขนาดร้านใหญ่
*   ห้องน้ำก่อนเข้าทาง
*   อาหารบางอย่าง (ลาบไข่ต้ม, ทอดมันหัวปลี, พะแนงห่อไข่)
*   ราคาอาหารที่สูงเกินไป
*   มีของหวานให้ฟรี

ขั้นตอนที่ 2: ระบุหัวข้อหลักที่กล่าวถึง

*   ขนาดร้าน
*   คุณภาพอาหาร (โดยเฉพาะอาหารไทย)
*   ราคา

ขั้นตอนที่ 3: เลือก 3 keywords ที่สำคัญที่สุด

จากหัวข้อหลักที่กล่าวถึง ผมเลือกคำเหล่านี้เป็น keywords ที่สำคัญที่สุด:

1.  ร้านอาหาร (ขนาดใหญ่)
2.  ราคาแพง
3.  อาหารไทย

ขั้นตอนที่ 4: ตอบในรูปแบบ JSON

```json
{
  "keywords": ["ร้านอาหาร", "ราคาแพง", "อาหารไทย"]
}
```

หวังว่าคำตอบนี้จะเป็นประโยชน์นะครับ หากคุณมีคำถามเพิ่มเติมหรือต้องการให้ผมช่วยวิเคราะห์อะไรอีก โปรดแจ้งให้ทราบได้เลย

Review วันนี้ได้มีโอกาสไปนั่งซดกาแฟที่ร้านวาวี แถวๆอารีย์

ก็ได้ยินมาบ่อยๆละ จากหลายที่ แต่ที่บ่อยสุดก็จาก ...
text แน่นอนครับ ผมจะทำตามขั้นตอนที่คุณให้มาเพื่อสกัดคำหลักจากรีวิวนี้:

ขั้นตอนที่ 1: อ่านรีวิวและเข้าใจความหมาย

รีวิวนี้พูดถึงประสบการณ์การไปดื่มกาแฟที่ร้าน "วาวี" ในบริเวณใกล้เคียงอารีย์ โดยเน้นที่รสชาติ กาแฟ บรรยากาศ การบริการ และราคา

ขั้นตอนที่ 2: ระบุหัวข้อหลักที่กล่าวถึง

*   รสชาติกาแฟ (ลาเต้, Coco ปั่น)
*   บรรยากาศร้าน
*   การบริการ
*   ราคา

ขั้นตอนที่ 3: เลือก 3 keywords ที่สำคัญที่สุด

จากหัวข้อหลักที่กล่าวถึง ผมเลือกคำหลักดังนี้:

1.  กาแฟ
2.  บรรยากาศ
3.  วาวี

ขั้นตอนที่ 4: ตอบในรูปแบบ JSON

```json
{
  "keywords": ["กาแฟ", "บรรยากาศ", "วาวี"]
}
```

หวังว่าคำตอบนี้จะเป็นประโยชน์นะครับ หากคุณมีคำถามเพิ่มเติมหรือต้องการให้ผมช่วยอะไรอีก สามารถบอกได้เลยครับ

In [98]:
from pydantic import BaseModel, Field
from langchain_core.output_parsers import JsonOutputParser

class ReviewKeywords(BaseModel):
    keywords: str = Field(
        ...,  # Required field
        description="3 keywords separated by comma",
        examples=["กาแฟ, บรรยากาศ, ราคา"]
    )

class KeywordsExtraction(BaseModel):
    extracted_qualities: ReviewKeywords

In [99]:
keywords_parser = JsonOutputParser(pydantic_object=KeywordsExtraction)

In [100]:
keyword_extract = keyword_prompt | llm3 | keywords_parser

In [101]:
%%time
results = []
for review in sample_reviews:
    text = keyword_extract.invoke({"review": review})
    results.append({"review": review, "text": text})

CPU times: user 264 ms, sys: 15.1 ms, total: 279 ms
Wall time: 15.4 s

In [102]:
results[0]['text']['keywords']

['ราคา', 'อาหารไทย', 'รสชาติ']

In [103]:
results[1]['text']['keywords']

['กาแฟ', 'บรรยากาศ', 'บริการ']

In [105]:
llm3 = ChatOllama(
    model="scb10x/typhoon2.1-gemma3-4b",
    temperature=0.05
)

keyword_extract = keyword_prompt | llm3 | keywords_parser

In [106]:
%%time
results = []
for review in sample_reviews:
    text = keyword_extract.invoke({"review": review})
    results.append({"review": review, "text": text})

CPU times: user 308 ms, sys: 23.9 ms, total: 332 ms
Wall time: 14.5 s

In [107]:
results[0]['text']['keywords'], results[1]['text']['keywords']

(['ราคา', 'รสชาติ', 'ขนาด'], ['กาแฟ', 'บรรยากาศ', 'รสชาติ'])

In [108]:
keyword_prompt = PromptTemplate(
    template="""จาก Review ต่อไปนี้
    Extract keywords 3 keywords เท่านั้น ที่เป็นตัวแทนของ Review นี้ได้ดีที่สุด

    Review: {review}

    ตอบในรูปแบบ JSON โดยมีคีย์เป็น 'keywords'
    และค่าเป็นข้อความที่ดึงได้คั่นด้วย comma
    เช่น {{"keywords": "กาแฟ, บรรยากาศ, ราคา"}}

    หากไม่พบข้อมูลให้ตอบ 'ไม่ระบุ'
    """
)

In [109]:
keyword_extract = keyword_prompt | llm3 | keywords_parser

In [110]:
inputs = [{"review": r} for r in sample_reviews]

In [111]:
%%time
results = keyword_extract.batch(inputs)
results

CPU times: user 30.6 ms, sys: 4.29 ms, total: 34.9 ms
Wall time: 2.39 s

[{'keywords': 'ราคา, บรรยากาศ, ไข่ต้ม'},
 {'keywords': 'กาแฟ, บรรยากาศ, รสชาติ'}]

In [112]:
sample_reviews_1000 = coffee_reviews_df['column0'].head(1000).tolist()
inputs_1000 = [{"review": r} for r in sample_reviews_1000]

BATCH_SIZE = 8

results_1000 = []

In [113]:
from tqdm import tqdm

In [114]:
for i in tqdm(range(0, len(inputs_1000), BATCH_SIZE), desc="Extracting keywords"):
    batch = inputs_1000[i:i+BATCH_SIZE]
    outputs = keyword_extract.batch(batch)
    for inp, out in zip(batch, outputs):
        results_1000.append({"review": inp["review"], "text": out})

Extracting keywords: 100%|██████████| 125/125 [18:42<00:00,  8.98s/it]

In [115]:
for result in results_1000[0:1000]:
    print(result['text']['keywords'])

ราคา, บรรยากาศ, ไข่ต้ม
กาแฟ, บรรยากาศ, รสชาติ
โดนัท, น้ำตาล, รสชาติ
ปลาซาบะ, ไข่ตุ๋น, ราคาคุ้มค่า
โดนัท, Original Glazed, คิว
วังพญาไท, นรสิงห์, คาเฟ่
อาหารทะเล, ราคา, บรรยากาศ
กาแฟ, เค้ก, พนักงาน
Shibuya Honey Toast, ฮันนี่ โทสท์, ราคา
คาเฟ่, วานิลลา, คาโบนาร่า
กาแฟ, เค้ก, สมูตตี้
กาแฟ, บรรยากาศ, สลัดไก่
ไอศครีม, ชิม, ราคา
ก๋วยเตี๋ยว, เอกมัย, ปอเปี๊ยะ
ข้าวห่อไข่, เมนู, บรรยากาศ
หวาน, ช็อกโกแลต, เครื่องใช้
บรรยากาศ, ปลั๊กไฟ, กาแฟ
กาแฟ, อาหาร, โปรโมชั่น
ปลาเผา, น้ำจิ้ม, แกงเลียง
ติ่มซำ, 24 ชั่วโมง, ราคา
รสชาติ, บรรยากาศ, สเต็ก
ราคา, พาสต้า, บรรยากาศ
พิซซ่า, คาลามารี, ซัลมอน
บรรยากาศ, ราคา, ข้าวผัด
กาแฟ, บรรยากาศ, ราคา
บรรยากาศ, อาหาร, ที่จอดรถ
ขนมสายไหม, รสชาติ, บรรยากาศ
กาแฟ, ราคา, บริการ
บริการ, พนักงาน, จานเปล่า
บรรยากาศ, ขนมปัง, ชา
ชาบู, ราคา, บรรยากาศ
โรงพยาบาล, บรรยากาศ, อาหาร
ข้าวห่อไข่, เมนูหลากหลาย, ราคา
ติ่มซํา, ขนมผักกาด, ปลาเต้าซี่
แกะ, เนื้อแกะ, รสชาติ
เค้ก homemade, mocha choc cake, เค้กแครอท
ปากน้ำ, กาแฟ, ร้าน Chubby
ร้านกาแฟ, บรรยากาศเงียบสงบ, ราคาไม่แพง
ราคา, ความหลากหลาย, รสชาติ
กาแฟ, คาราเมล มัคคีอาโต้, ราคา
อาหารญี่ปุ่น, ราคา, ความหลากหลาย
หัวหิน, ร้านกาแฟ, บรรยากาศ
บรรยากาศ, เบเกอรี่, ราคา
บรรยากาศ, กาแฟ, บัว
บรรยากาศ, บราวนี่, ไอศครีม
บรรยากาศ, อาหารอิตาเลี่ยน, บรรยากาศ
บรรยากาศ, สลัด, อาหารอิตาเลียน
ไข่, เบค่อน, นิมมาน
เค๊ก, นิมมาน, การบริการ
น้ำปั่น, ราคา, สั่ง
กาแฟ, ราคา, บรรยากาศ
ก๋วยจั๊บ, ร้านโจ๊ก, ขนมปังฝรั่งเศส
เครป, บรรยากาศ, ราคา
ร้านอาหาร, สปาเก๊ตตี้, โลตัส
กาแฟ, บรรยากาศ, อาหาร
ร้านอาหาร, กาแฟ, สเต็ก
เค้ก, กาแฟ, ราคา
ร้านอาหาร, สลัด, คาร์โบนาร่า
ข้าวห่อไข่, รสชาติ, ราคา
บุฟเฟต์, ชาบู, ราคา
แตงโม, น้ำแตงโมปั่น, สารอาหาร
ร้านกาแฟ, บรรยากาศ, ราคา
ข้าวผัดเขียวหวานไก่, บรรยากาศ, บริการ
คาเฟ่, กาแฟ, บรรยากาศ
ราคา, ช็อกโกแลตปั่น, บริการ
ข้าวไข่ข้น, สุขภาพ, รสชาติ
คาเฟ่, บรรยากาศชิล, ขนมปังกระเทียม
ร้านกาแฟ, บรรยากาศ, กาแฟสด
ไอศครีม, แนว, อร่อย
อาหารไทย, ร้านอาหาร, กลิ่นอาหาร
บรรยากาศ, อาหาร, กาแฟ
ชอกโกแลตร้อน, ราคา, โปรโมชั่น
กาแฟ, กาแฟไทยโบราณ, บรรยากาศ
ราคา, อาหาร, รอคอย
บรรยากาศ, อาหารเวียดนาม, พนักงานเอาใจใส่
ราคา, ชา, ขนมปัง
บรรยากาศ, ราคา, กาแฟ
ร้าน CP, กาแฟ, บรรยากาศ
บรรยากาศ, เค้ก, ราคา
ลอดช่อง, ก๋วยเตี๋ยว, ขนุน
ข้าวแกงใต้, ร้านกาแฟ, ที่จอดรถ
กาแฟ, บรรยากาศ, ราคา
กาแฟ, บรรยากาศ, พนักงาน
กาแฟ, กาแฟสด, ขนม
แมว, บรรยากาศ, ชา กาแฟ
อาหารไทย, ปลาช่อนเผา, ร้านใหม่
บุฟเฟต์, ปลาแซลมอน, ไอติม
ร้านกาแฟ, อาหารง่ายๆ, กับแกล้ม
กาแฟ, อาหาร, ผัดไท
กาแฟ, บรรยากาศ, ที่จอดรถ
สตาร์บัคส์, มอคค่า, รสชาติ
ก๋วยเตี๋ยว, ข้าวคลุกกะปิ, บรรยากาศ
กาแฟ, บรรยากาศ, เครื่องดื่ม
กาแฟ, บรรยากาศ, สัมมากร
กาแฟ, ราคา, พนักงาน
บรรยากาศ, กาแฟ, รสชาติ
ราคา, คุณภาพ, สลัดแซลมอน
อาหารเวียดนาม, น้ำจิ้ม, ราคา
ขนมปังปิ้ง, น้ำปั่น, ราคา
ญี่ปุ่น, chirashi don, buta steak
เป็ดพะโล้, ราคา, ก๋วยเตี๋ยวเป็ด
บรรยากาศ, กาแฟ, ราคา
อาหาร, รสชาติ, บรรยากาศ
ก๋วยเตี๋ยวเป็ด, ก๋วยเตี๋ยวน่องไก่, ขนมปังสังขยา
เค้ก, หน้าตา, รสชาติ
ร้าน, บรรยากาศ, กาแฟ
เป็ด, น้ำจิ้ม, ข้าว
มอเตอร์เวย์, ชลบุรี, เย็นตาโฟ
กาแฟ, บรรยากาศ, กาแฟเย็น
อาหารอีสาน, รสชาติ, บริการ
คาเฟ่, มัทฉะ, เค้ก
อเมซอน, กาแฟ, บรรยากาศ
ชานม, เครื่องดื่ม, ท็อปปิ้ง
พายโฮมเมด, ช็อกโกแลต, มะนาว
กาแฟ, อาหาร, ล้างรถ
กาแฟ, บราวนี่, ราคา
แมว, บรรยากาศ, ราคา
ปาร์ตี้, เบียร์, อาหาร
กาแฟ, บรรยากาศ, เค้ก
นมสด, ขนมปังปิ้ง, ราคา
แมว, คาเฟ่, บรรยากาศ
มาการอง, ชาเขียว, บรรยากาศ
เค้ก, บรรยากาศ, ราคา
คาเฟ่แมว, แมว, บรรยากาศ
เครื่องดื่ม, ไข่มุก, ชานม
ร้านกาแฟ, วัฒนธรรม, อาหาร
กาแฟ, บรรยากาศ, รสชาติ
ร้านอาหาร, พม่า, ก๋วยเตี๋ยว
กาแฟ, ปางขอน, บรรยากาศ
ร้านกาแฟ, บรรยากาศ, ราคา
ราคา, บรรยากาศ, อาหาร
ร้านกาแฟ, บรรยากาศ, อาหาร
กาแฟ, บรรยากาศ, ผ่อนคลาย
บรรยากาศ, กาแฟ, เครื่องดื่ม
บรรยากาศ, ราคา, อาหาร
บรรยากาศ, กาแฟ, ราคา
อาหารตามสั่ง, ต้มแซบกระดูกอ่อน, รสชาดอาหาร
บรรยากาศ, มัทฉะลาเต้, ที่จอดรถ
ร้านอาหาร, นักศึกษา, ความสุข
กาแฟ, ราคา, บรรยากาศ
ร้านนม, ค่ำ, ราคา
อาหารไทยฟิวชั่น, ปอเปี๊ยะแฮมชีส, เค้ก
บรรยากาศคลาสสิค, สลัดทูน่า, คาลาเมลลาเต้
ร้านกาแฟ, บรรยากาศ, ราคา
บรรยากาศ, กาแฟ, ราคา
กาแฟ, รสชาติ, ราคา
อาหาร, สุขุมวิท, บรรยากาศ
กาแฟ, อาหาร, บรรยากาศ
ข้าวไข่ข้น, ข้าวผัด, กาแฟ
บรรยากาศ, กาแฟ, พระพิฆเนศ
รสชาติ, เนื้อ, ข้าว
กาแฟ, บรรยากาศ, วิวทะเล
บรรยากาศ, กาแฟ, เค้ก
อาหารเช้า, ติ่มซำ, ปอเปี๊ยะทอด
คัพเค้ก, สยามพารากอน, Dilmah
ชา, กาแฟ, ไข่มุก
บรรยากาศ, สปาเก็ตตี้, กาแฟ
ร้านอาหารเช้า, อ่าวนาง, ข้าวหมกไก่
กาแฟ, Tamp, Mocha
สปาเก็ตตี้, ไส้กรอกอิตาเลียน, รสชาติเค็ม
แมว, เค้ก, พักผ่อน
ก๋วยเตี๋ยว, ไก่, น้ำซุป
กาแฟ, พนักงาน, บรรยากาศ
ร้านกาแฟ, บรรยากาศ, เค้ก
ห้าง, ล้างรถ, กาแฟ
ร้านกาแฟ, บรรยากาศ, อาหาร
ร้านอาหารอิตาเลี่ยนไทย, บรรยากาศ, อาหาร
คาเฟ่, เค้กชาเขียว, บรรยากาศ
อิซากายะ, ซูซิ, เครื่องดื่ม
แมว, บราวนี่, บริการ
ร้านกาแฟ, อาหารไทย, บรรยากาศ
อาหาร, โฮมเมด, ราคา
แมว, บรรยากาศ, อาหาร
บุฟเฟต์, เค้ก, บรรยากาศ
บรรยากาศ, กาแฟ, ข้าวหน้าไก่
อาหารอิตาเลียน, สปาเก็ตตี้, บรรยากาศ
อาหาร, ความสะอาด, บริการ
ล้างรถ, กาแฟ, บรรยากาศ
บรรยากาศ, แมว, ขนม
ก๋วยเตี๋ยว, น้ำซุป, อร่อย
บรรยากาศ, ครัวซอง, ชารสมะม่วง
กาแฟ, ครัวซอง, บรรยากาศ
ทรูคอฟฟี่, วนิลาทวิสครีม, น้ำแข็ง
บรรยากาศ, กาแฟ, เค้ก
บรรยากาศ, wifi, ตู้ขนม
บุฟเฟต์, สุกี้, ราคา
อาหารทะเล, กุ้งแม่น้ำ, บรรยากาศ
Ice caramel macchiato, กาแฟ, แซนวิชแฮมชีส
ชาเขียว, มอคค่า, บริการ
ไข่กระทะ, ซอสแม็กกี้, อาหารเช้า
กาแฟ, ราคา, บรรยากาศ
พาย, กาแฟ, ราคา
สลัดผักย่าง, สมูทตี้, ออร์แกนิค
ร้านอาหาร, ขนมปัง, กลิ่นหอม
ร้านกาแฟ, บรรยากาศ, เครื่องดื่ม
กาแฟ, เค้ก, วาฟเฟิล
อาหารไทย, พาสต้า, ข้าวผัด
กาแฟ, เค้ก, บรรยากาศ
กาแฟ, ครัวซองต์, อิตาเลียนโซดา
ก๋วยเตี๋ยว, หมูน้ำตก, บรรยากาศ
สไตล์, กาแฟ, ราคา
ร้าน, กาแฟ, บรรยากาศ
ร้านกาแฟ, บรรยากาศ, ชาเย็น
ชาไข่มุก, รสชาติ, เปิดมานาน
คาเฟ่, บรรยากาศ, เบเกอรี่
Macchiato, ความผิดหวัง, กาแฟโบราณ
กาแฟ, กลิ่นหอม, เค๊ก
อาหาร, พนักงาน, บรรยากาศ
ปังภูเขาไฟ, อร่อย, เย็น
บรรยากาศ, กาแฟ, ครัวซอง
ไข่กระทะ, ขนมปัง, ราคา
บรรยากาศ, ชาไทย, เซลฟเซอร์วิส
อาหาร, ทรรศนียภาพ, ราคา
ชีทเค้ก, ราคา, ชา
บรรยากาศ, การตกแต่ง, บริการ
บรรยากาศ, กาแฟ, เครื่องดื่ม
ร้านกาแฟ, บรรยากาศ, ราคา
ก๋วยเตี๋ยว, เค้ก, รสชาติ
วิวทะเล, บรรยากาศ, แกงส้มปลาใบกะเพรา
กาแฟ, ลาเต้เย็น, รสชาติ
อาหารอิตาเลียน, คาร์โบนาล่า, เค้ก
ด่านพระรามเก้า, นมสดปั่น, การสั่งล่วงหน้า
อาหารไทย, สเต็กส์, อาหารเช้า
บรรยากาศ, กาแฟ, เค้ก
บรรยากาศ, กาแฟ, เค้ก
กาแฟ, ราคา, บรรยากาศ
ร้านอาหาร, Strawberry Honey Smoothie, Fruit Tart
บรรยากาศ, ราคา, หมูน้ำตก
กาแฟ, บรรยากาศ, ครัวซอง
บรรยากาศ, นั่งสบาย, ชา
บรรยากาศ, การบริการ, เมนู
ขนมปัง, ออริจินอล, กาแฟ
ร้านกาแฟ, บรรยากาศ, กาแฟ
ก๋วยเตี๋ยวตำลึง, อาหารตามสั่ง, ก๋วยเตี๋ยวต้มยำ
พาย, รสชาติ, กาแฟ
เบอร์เกอร์, อาหาร, ราคา
รังนก, ราคา, บรรยากาศ
อาหารฝรั่ง, ราคา, รสชาติ
มัฟฟิ่น, ช็อกโกแล็ต, เค็กทีรามิสุ
กาแฟ, บรรยากาศ, Waffle
กาแฟ, มอคค่าเย็น, บรรยากาศ
มื้อเช้า, ไข่กะทะ, ปาท่องโก๋
เค้ก, บรรยากาศ, กลิ่นอาหาร
เค้ก, บรรยากาศ, พนักงาน
กาแฟ, บรรยากาศ, อาหาร
ก๋วยเตี๋ยว, ต้มยำ, หมูกรอบ
บรรยากาศ, ชาเขียว, อาหาร
บรรยากาศ, ราคา, กาแฟ
บรรยากาศ, การบริการ, กาแฟ
บรรยากาศ, เค้ก, ราคา
ร้านกาแฟ, บรรยากาศ, เครื่องดื่ม
ชาไทย, น้ำจิ้ม, หมูย่าง
คอนโด, ร้านกาแฟ, นมขนมปังปิ้ง
ชา, เครื่องดื่ม, ราคา
กาแฟสด, เค้กมะพร้าวอ่อน, ราคา
บรรยากาศ, ขนมหวาน, ราคา
บรรยากาศ, เครื่องดื่ม, เค้ก
ร้าน, คัพเค้ก, บรรยากาศ
ราคา, บรรยากาศ, อาหารหลากหลาย
ติ่มซำ, ราคา, สาขา
ร้านกาแฟ, บรรยากาศ, ราคา
ร้าน, บรรยากาศ, กาแฟ
ฮันนี่โทสต์, นมสด, โปรโมชั่น
ก๋วยเตี๋ยว, แคบหมู, บรรยากาศ
ก๋วยจั๊บน้ำใส, เครื่องใน, ความกลมกล่อม
บรรยากาศ, ราคา, เค้ก
กาแฟ, ราคา, ขนมปัง
เค้ก, ทีรามิสุ, ญี่ปุ่น
บรรยากาศ, ไอศครีม, เค้ก
บรรยากาศ, อาหาร, ราคา
ร้านกาแฟ, กาแฟ, บรรยากาศ
สาขา, กาแฟ, สถานศึกษา
บรรยากาศ, กาแฟ, ราคา
ไอติมโมจิ, บรรยากาศ, ราคา
ร้านอาหารไทย, สวนผึ้ง, ราคา
บรรยากาศ, นักท่องเที่ยว, ราคา
กาแฟ, บรรยากาศ, ราคา
บรรยากาศ, กาแฟ, เค้ก
กาแฟ, บรรยากาศ, สไตล์หวานมัน
กาแฟ, บรรยากาศ, ไอศครีม
ราคา, อร่อย, สนามบิน
ชาไต้หวัน, ชาอู่หลง, ราคา
ร้านอาหาร, ชานม, ราคา
สเต็ก, ทาปาส, แฮมสเปน
เครปเค้ก, ไอศกรีม, ราคา
อาหารอิตาเลียน, เบเกอรี่, ราคา
กาแฟ, บรรยากาศ, เค้ก
บรรยากาศ, กาแฟ, การบริการ
ผักออแกนิกส์, อาหารเพื่อสุขภาพ, บรรยากาศ
คัพเค้ก, วัตถุดิบ, การตกแต่ง
เค้ก, บรรยากาศ, ราคา
starbucks, บรรยากาศ, เมนูใหม่
บรรยากาศ, เค้ก, ราคา
บรรยากาศ, กาแฟ, บรรยากาศเป็นกันเอง
อาหารญี่ปุ่น, ปลาแซลมอน, ซุปมิโซะ
นมสด, ขนมปัง, ราคา
บรรยากาศ, ชาเขียว, เค้ก
บรรยากาศ, กาแฟ, รสชาติ
กาแฟสด, ชา, มะดันดอง
กาแฟ, เค้ก, ราคา
วาฟเฟิล, ช็อคโกแลต, ไอติม
บรรยากาศ, เจ้าของร้าน, ชา
ขนมปังชีส, ข้าวอบไข่, แฮม
กาแฟ, รสชาติ, ส่งถึงที่
ร้านกาแฟ, สาขา, เครื่องดื่ม
อาหารอิตาเลี่ยน, บริการ, ราคา
กาแฟ, โจ๊ก, บรรยากาศ
ตรัง, กันตังติ่มซำ, ขนมจีน
กาแฟ, สถานีขนส่งเอกมัย, บรรยากาศ
บรรยากาศ, ราคา, อาหาร
ชา, Earl Grey, ICE Chocolate
คาเฟ่, บรรยากาศ, อาหาร
ไอศครีม, ชอกโกแลต, บรรยากาศ
กาแฟ, บรรยากาศ, รสชาติ
กาแฟ, ลาเต้, สเต็ก
บรรยากาศ, กาแฟ, สไตล์ Cafe Zakka
เบเกอรี่, อาหาร, การตกแต่งร้าน
ก๋วยเตี๋ยว, ไก่, ราคา
Tom n Tom, กาแฟ, บริการตัวเอง
รีสอร์ท, กาแฟ, บรรยากาศ
กาแฟ, อัฟโฟกัสโต้, เค้ก
กาแฟ, มัจฉะ, บรรยากาศ
ร้านริมแม่น้ำ, กาแฟสด, อาหารปลา
กาแฟ, บรรยากาศ, อาหาร
บรรยากาศ, สัตว์เลี้ยง, อาหารอร่อย
กาแฟ, ราคา, บริการ
cupcake, ช็อกโกแลต, รสชาต
บรรยากาศ, กาแฟ, ศิลปะ
กาแฟ, เมล็ดกาแฟ, รถตู้
บรรยากาศ, อาหารญี่ปุ่น, ของหวาน
บรรยากาศ, ราคา, ขนมหวาน
พาสต้า, บรรยากาศ, ราคา
โมจิ, ไอศครีม, ราคา
ข้าวซอย, ก๋วยเตี๋ยว, ที่จอดรถ
Bibimbap, น้ำซุป, น้ำแข็งใส
ร้านใหม่, กาแฟ, ขนม
ปลาสด, น้ำจิ้มแซ่บ, ราคา
ไข่กระทะ, บรรยากาศ, อาหารเช้า
ร้านกาแฟ, บราวนี่, โครงการปาล์มมารีน่า
มุก, สาขา, เชียงใหม่
แมว, ทาสแมว, บรรยากาศ
Starbucks Reserve, บรรยากาศ, Cone Brew
มังสวิรัติ, บรรยากาศ, ร้านกาแฟ
บรรยากาศ, สงบ, กาแฟ
กาแฟ, โจ๊ก, ราคา
ผักออร์แกนิค, สลัด, กาแฟ
บรรยากาศ, กาแฟ, Wifi
กาแฟ, บรรยากาศ, ราคา
โฮมเมด, สลัด, ไอศกรีม
บรรยากาศ, อาหาร, พนักงาน
บรรยากาศ, กาแฟ, บรรยากาศดี
บรรยากาศ, ผักออแกนิค, การบริการ
กาแฟ, รสชาติ, ปั๊มปตท.
ร้านอาหาร, กุนเชียงทอด, ข้าวราดแกง
กาแฟ, บรรยากาศ, ราคา
นมสด, ไอศครีม, โยเกิร์ต
ร้านกาแฟ, บรรยากาศ, กาแฟ
ร้านกาแฟ, เค้ก, บรรยากาศ
อร่อย, วัตถุดิบดี, ไก่ทอด
กาแฟ, ราคา, บรรยากาศ
เค้ก, คุกกี้, บราวนี่
ไอศครีมนม, สตรอเบอรี, ราคา
บรรยากาศ, วิว, กาแฟ
ร้านอาหาร, ไทย, อิตาลี
ไข่กระทะ, บรรยากาศ, ราคา
น้ำ, ราคา, ชาเขียว
ราคา, กาแฟ, มัฟฟิน
กาแฟ, บางจาก, พนักงาน
โฮมเมด, สเต๊ก, อาหารเช้า
น้ำปั่น, ผลไม้, ราคา
กาแฟ, บรรยากาศ, waffle
บรรยากาศ, กาแฟ, บราวนี่
สวนผึ้ง, กาแฟ, บรรยากาศ
บรรยากาศดี, อาหารอร่อย, ราคา
ไอติม, รสชาติ, ขนาด
บรรยากาศ, ราคา, ชีสเค้ก
ชา, หวาน, รสชาติ
ไอศครีม, โปรโมชั่น, มอคค่า
บรรยากาศ, โต๊ะ, กาแฟ
บรรยากาศ, กาแฟ, ราคา
หมูปิ้ง, ราคา, รสชาติ
โดนัท, น้ำตาล, กาแฟ
อาหารทะเล, กรรเชียงปูนึ่ง, บรรยากาศ
ชา, ชานม, ไต้หวัน
ร้าน, ราคา, ไอศกรีม
ร้านกาแฟโบราณ, ชามะนาว, บรรยากาศ
สเต็ก, ยำสลัดหมู, ขนมปังกระเทียม
สไตล์โมเดิร์น, ข้าวห่อไข่, ราคาแพง
บรรยากาศ, กาแฟ, บรรยากาศโบราณ
ห้าง Union Mall, น้ำหวาน, ราคา
รสoriginal, บรรยากาศ, ราดน้ำตาล
ขนมปัง, ราคา, นมสด
บรรยากาศ, อาหาร, เค้ก
บรรยากาศ, กาแฟ, คุกกี้
ข้าวต้มกระเพาะหมู, ข้าวต้มซี่โครงหมู, ข้าวต้ม
กาแฟ, บาริสต้า, ราคา
เค้ก, มาการอง, บรรยากาศ
ข้าวหน้าเป็ด, เป็ดย่าง, ร้านประจำ
ตลาด Green Market, มหากาแฟ, กาแฟ
กาแฟโบราณ, น้ำแดง, เฮลบลูบอย
บรรยากาศ, ดนตรี, อาหาร
ชา, กาแฟ, บรรยากาศ
กาแฟ, ราคา, บรรยากาศ
ร้าน, บรรยากาศ, กาแฟ
จักรยาน, บรรยากาศ, โปรโมชั่น
บรรยากาศ, รสชาติ, ราคา
ร้านอาหาร, สุขภาพดี, ราคา
ร้านกาแฟ, True coffee, เอสเพรสโซ่ปั่น
ร้าน, อาหาร, กาแฟ
ร้านกาแฟ, บรรยากาศ, การทำงาน
บรรยากาศ, กาแฟ, การบริการ
วุ้นใบเตย, ชีสเค้ก, ชานม
รสชาติ, รสสัมผัส, ชีสเค้ก
ดนตรี, ชา, อู่หลง
บุฟเฟต์, อาหารไทย, อาหารทะเล
กาแฟโบราณ, บรรยากาศชิว, ตลาดนัด
ขนมปัง, ราคา, กลิ่นแปลก
วินเทจ, กาแฟ, เค้ก
ร้านอาหาร, อาหารอร่อย, ครอบครัว
ล้างรถ, กาแฟ, อาหาร
ข้าวห่อไข่, บรรยากาศ, สไตล์ญี่ปุ่น
McDonald's, หัวหิน, เฟรนช์ฟรายด์
ร้าน, บรรยากาศ, ราคา
ราคา, บะหมี่, อิ่ม
บรรยากาศ, กาแฟ, บองมาเช่
พนักงานใหม่, การบริการ, เครื่องดื่ม
กาแฟ, บรรยากาศ, ราคา
สนามบิน, อ่าวพังงาน, อาหาร
บริการ, กาแฟ, กรานิต้า
บรรยากาศ, ราคา, สลัดผัก
อาหาร, บรรยากาศ, ที่จอดรถ
ร้านมิสเตอร์ดอย, ชาดำเย็น, การบริการ
ร้าน, กาแฟ, สั่งอาหาร
กาแฟ, บรรยากาศ, ดอกไม้
กาแฟ, ขนมปังกระเทียม, บรรยากาศ
ขนม, กาแฟ, โมจิเค้ก
สเต็ก, น้ำสลัด, บรรยากาศ
พนักงาน, ฟองนม, ราคา
กาแฟ, ราคา, บรรยากาศ
เบอร์เกอร์, มอเตอร์เวย์, ห้องน้ำ
ปาท่องโก๋, น้ำเต้าฮู้, โจ๊ก
อาหารเช้า, แม่น้ำโขง, ไข่ลวก
กาแฟ, บรรยากาศ, สลัด
ร้าน, กาแฟ, ข้าวห่อไข่
ชีสเค้ก, รสชาติดุเดือด, หวานน้อย
บรรยากาศ, เค้ก, ชา
เบเกิล, ไส้, อร่อย
กาแฟถุงกระดาษ, ราคา, กาแฟโบราณ
กาแฟ, ราคา, บรรยากาศ
กาแฟ, ชาเขียว, บรรยากาศ
ถ่ายรูป, กาแฟ, โกโก้
ไอศกรีม, โฮมเมด, บรรยากาศ
กาแฟ, บรรยากาศ, รสชาติ
อาหารฝรั่ง, brunch, egg benedict
บรรยากาศ, วังพญาไท, กาแฟ
โรตี, กาแฟสด, Honey Toast
Disneyland, อาหาร, แกงกระหรี่
ขนมไทย, บรรยากาศ, ราคา
รสชาติ, เมนูหลากหลาย, เค้ก
คาเฟ่, บรรยากาศ, ราคา
กาแฟ, เข้มข้น, รสชาติดีเยี่ยม
บรรยากาศ, กาแฟ, พุดดิ้ง
คาลาเมล, ไอศกรีม, ช็อกโกแลต
ก๋วยเตี๋ยวหมูสับไข่ดิบ, บรรยากาศ, ราคา
ข้าวราดกระเพรา, หมูทอด, กาแฟ
ชีสเค้ก, ราคา, สตรอเบอรี่
ร้านกาแฟ, บรรยากาศ, โชว์รูมรถยนต์เบนซ์
กาแฟ, ราคา, คาเฟอีน
บรรยากาศ, ราคา, กระต่าย
กาแฟ, บรรยากาศ, เค้ก
อุดรธานี, กาแฟ, อาหารเช้า
กาแฟ, เครื่องกรอง, แก้วใส
บรรยากาศ, กาแฟ, บรรยากาศดี
ร้านอาหาร, สลัดสาหร่าย, บรรยากาศ
อาหารเช้า, ออมเลท, แซนวิช
เครป, ของหวาน, บราวนี่
ร้านกาแฟ, บรรยากาศ, ราคา
อาหารเช้า, western, ญี่ปุ่น
กาแฟ, บรรยากาศ, เครื่องปั่น
ชา, กาแฟ, ชาเย็น
ก๋วยเตี๋ยว, อาหารหลากหลาย, เด็กนักศึกษา
ช็อกโกแล็ตปั่น, ร้านกาแฟ, IKEA
กาแฟ, ราคา, ฮันนี่โทส
ถนนวิทยุ, กาแฟ, ราคา
บรรยากาศ, อาหารจานเดียว, แกะ
ร้านกาแฟ, บรรยากาศ, อาหาร
สตรอเบอรี่, สปา, บรรยากาศ
กาแฟ, ไอศครีม, ราคา
กาแฟ, บรรยากาศ, กาแฟไทย
บรรยากาศ, อาหาร, เครื่องดื่ม
บรรยากาศ, เค้ก, กาแฟ
เค้กมะพร้าวอ่อน, ทาร์ตไข่, กาแฟ
รอคิว, บรรยากาศ, ราคา
บรรยากาศ, กาแฟ, 24 ชม.
กาแฟ, รสชาติ, ราคา
ซุปผักโขม, เค้กส้ม, crab salad sandwich
พายหมูแดง, กาแฟ, April's Bakery
คาเฟ่, ไอศกรีม, ราคา
ราคา, ขนาด, รสชาติ
กาแฟ, บรรยากาศ, เปิด 24 ชั่วโมง
กาแฟ, กาแฟปั่น, รสชาติ
เค้ก, สโคน, ชา
บรรยากาศ, กาแฟ, จำนวนลูกค้า
กาแฟ, อเมริกาโน่, ไอศครีม
บรรยากาศ, โปรโมชั่น, อาหาร
ร้านกาแฟ, บรรยากาศ, อาหาร
กาแฟ, โกโก้, ชานม
เสต็ก, ราคา, บรรยากาศ
กาแฟ, น่ารัก, ร้าน
ร้าน, บรรยากาศ, กาแฟ
กาแฟ, ราคา, บริการ
กาแฟ, บรรยากาศ, ขนม
บุฟเฟต์, ยากินิคุ, เครื่องดื่ม
กาแฟ, บรรยากาศ, การบริการ
รสชาติ, บรรยากาศ, ราคา
คาเฟ่แมว, แมว, สวนสัตว์
บุฟเฟต์, อาหารไทย, บรรยากาศ
ร้านกาแฟ, บรรยากาศ, กาแฟ
กาแฟ, โปรโมชั่น, ช้อปปิ้ง
บรรยากาศ, ไทย, เบเกอรี่
อาหารอีสาน, ส้มตำ, ไส้ย่าง
ร้านกาแฟ, บรมราชชนนี, คาปูชิโน
ร้านกาแฟ, สุขุมวิท, ราคา
ขนมไทย, โฮมเมด, คาเฟ่
บรรยากาศ, ชาเขียว, เบเกอรี่
อาหารไทย, เค้ก, ราคา
กาแฟโบราณ, ราคาประหยัด, อ่างศิลา
บรรยากาศ, เค้ก, ร้านกาแฟ
บรรยากาศ, กาแฟ, อัธยาศัยดี
อาหารญี่ปุ่น, lunch set, โมจิ
ร้านอาหารตามสั่ง, หมี่ฮกเกี้ยน, ผัดซีอิ๊ว
pizza, parma ham, tiramisu
ร้านกาแฟ, สลัดทุน่า, บรรยากาศ
กาแฟ, บรรยากาศ, ออสเตรเลีย
พายมะนาว, รสชาติ, ราคา
ราคา, ช็อกโกแลตมูส, บรรยากาศ
กาแฟ, โมเดิร์น, รสชาต
บรรยากาศ, กาแฟ, วิว
ดาคาซี่, ชา, ชานม
ร้านสวย, บรรยากาศดี, ใกล้เมือง
บรรยากาศ, กาแฟ, ร้าน
ทำเล, บรรยากาศ, คาราเมลครีมปั่น
บรรยากาศ, ร้านอาหาร, ทีรามิสุ
กาแฟ, คุกกี้, ราคา
กาแฟ, ดารา, บรรยากาศ
อาหารเช้า, ไข่กะทะ, กุนเชียง
เมนูหลากหลาย, โซดา, ท๊อปปิ้ง
กาแฟ, บรรยากาศ, พนักงาน
พาสต้า, บรรยากาศ, ราคา
กาแฟ, บรรยากาศ, รอรถ
อาหารจานเดียว, กาแฟ, ราคา
ราคา, รสชาติ, เค้ก
กาแฟ, ราคา, อร่อย
Starbucks, บรรยากาศ, WIFI
กาแฟ, บรรยากาศ, ราคา
อาหารอิตาเลี่ยน, บรรยากาศ, ราคา
กาแฟ, ราคา, โครงการ 89
บรรยากาศ, กาแฟ, ราคา
บรรยากาศ, เค้ก, ราคา
กาแฟ, JJ Market, ดึก
กาแฟ, ราคา, บรรยากาศ
อาหารเช้า, บัวระวง, เชียงใหม่
อาหารเช้า, ห้องอาหาร, ราคา
กาแฟ, ราคา, บรรยากาศ
บรรยากาศ, กาแฟ, คอร์สเรียน
ร้านกาแฟ, ไม้, ราคา
โปรโมชั่น, กาแฟ, พนักงาน
ข้าวห่อไข่, บรรยากาศ, รสชาติ
บรรยากาศ, อาหาร, กาแฟ
โรงพยาบาล, กาแฟ, อาหาร
กาแฟ, คุณภาพ, บรรยากาศ
ขนมปัง, ก๋วยเตี๋ยวเรือ, บรรยากาศ
ร้านกาแฟ, บรรยากาศ, พนักงาน
บรรยากาศ, กาแฟ, พิซซ่า
บรรยากาศ, อาหารอิตาเลี่ยน, กว้างขวาง
ร้านอาหาร, ไทย, ฝรั่ง
บรรยากาศ, เค้ก, พนักงาน
โอชายะ, ชาไข่มุก, ชาเขียว
อาหารไทย, ไข่ตุ๋น, เค้ก
สลัด, ปลาดอลลี่, ซีโครงหมู
เค้ก, บราวนี่, ชาเย็น
สเต็ก, สตอร์เบอร์รี่ปั่น, ราคา
บรรยากาศ, กาแฟ, หนังสือ
ขนม, กาแฟ, ราคา
ร้านกาแฟ, ดีไซน์, วงดนตรี
เบียร์, อาหาร, บรรยากาศ
บรรยากาศ, พนักงาน, กาแฟ
ร้านดัง, คนเยอะ, อาหารเช้า
บรรยากาศ, กาแฟ, บะกูด
บรรยากาศ, กาแฟ, เครื่องชงกาแฟ
กาแฟ, ลาเต้เย็น, บรรยากาศ
กาแฟ, บรรยากาศ, ราคา
บุฟเฟต์, สุขุมวิท, สลัดผัก
บรรยากาศ, อาหาร, ขนม
กาแฟ, บรรยากาศ, ราคา
ตลาดนัดสวนรถไฟ, แมว, อาหาร
กาแฟ, ราคา, บรรยากาศ
กาแฟ, บรรยากาศ, รสชาติ
สตรอว์เบอร์รี, คุกกี้, ราคา
ร้านทำเอง, แฟนบอล, อาหาร
ข้าวห่อใข่, เดมิกาซอส, ครีมบอลซอสกุ้ง
ร้านอาหาร, ก๋วยเตี๋ยว, ชาเย็น
สลัดกุ้ง, กาแฟ, ราคา
โปรโมชั่น, milk smoothie, บรรยากาศ
วัตถุดิบ, สดใหม่, ความหวาน
ซี่โครงหมูอบน้ำแดง, ฉู่ฉี่ปลา, บรรยากาศ
บรรยากาศ, กาแฟ, น้ำผลไม้
โดนัท, Krispy Kreme, รส Original
ข้าวตัง, มัลเบอรี่ปั่น, ของฝาก
ชานมไข่มุก, มุก, หวาน
บรรยากาศ, บราวนี่, เครื่องดื่ม
รสชาติ, บรรยากาศ, พ่อครัว
กาแฟ, ห้องประชุม, แซนวิซ
กาแฟมอคค่า, รสชาติอร่อย, โปรโมชั่น
เครป, อร่อย, กรอบ
ข้าวเปรี้ยว, ปลา, ชิ้นบาง
บรรยากาศ, ราคา, กาแฟ
บรรยากาศ, ราคา, อาหาร
กาแฟ, ราคา, บรรยากาศ
บรรยากาศ, กาแฟ, อินเทอร์เน็ต
บรรยากาศ, ราคา, รสชาติ
กาแฟสด, บรรยากาศ, ทะเลสาบ
บรรยากาศ, โฮมเมด, ราคา
กาแฟ, เข้มข้น, น่าน
Starbucks, กาแฟ, ราคา
ตลาดนัดรถโฟล์ค, กาแฟโบราณ, ราคา
ลูกชิ้นปลา, กาแฟ, ราคา
วาฟเฟิล, ช็อคโกแลต, กล้วยหอม
พุดดิ้ง, คาราเมล, เครป
ตุ๊กตา, กาแฟ, ทัวร์
ร้านกาแฟ, ตุ๊กตา, ทัวร์
กาแฟ, รสชาติ, ราคา
ร้านข้างทาง, ลูกกรุง, ก๋วยเตี๋ยว
บรรยากาศ, กาแฟ, ราคา
อาหาร, บรรยากาศ, เค้ก
แมว, ทองหล่อ, Red Velvet Cake
ไอศกรีม, โทสต์, ราคา
ดอยหลวง, อาหาร, ราคา
ปาท่องโก๋, ราคา, คิว
น้ำแข็งใส, โทสต์, วาฟเฟิล
บรรยากาศ, กาแฟ, ราคา
ร้าน True, กาแฟ, สะสมแต้ม
ร้านกาแฟ, นมสด, ราคา
จักรยาน, กาแฟ, ทริป
เค้ก, บรรยากาศ, กาแฟ
ชาไทย, ชานม, รามคำแหง
กาแฟ, บรรยากาศ, ราคา
กาแฟ, เอสเพรสโซ, ช็อกโกแล็ต
บรรยากาศ, อาหารอิตาเลียน, เบียร์
บรรยากาศ, wifi, อาหาร
สาขานี้, ที่จอดรถ, กลิ่นอเมซอน
ชานมไข่มุก, ราคาถูก, รสชาติ
ข้าว, ไข่ข้น, หมูย่าง
สปาเก็ตตี้, เผ็ด, ปริมาณน้อย
ร้านกาแฟ, อาหาร, บรรยากาศ
อพาร์เม้น, สระว่ายน้ำ, กาแฟ
พายมะพร้าว, กาแฟอเมริกัน, Homemade
บรรยากาศ, การตกแต่ง, ราคา
ร้านกาแฟ, สุกี้แห้ง, ราคาถูก
เค้ก, ชา, บรรยากาศ
ปาท่องโก๋, เชียงคาน, ราคา
เค้กมะพร้าว, บรรยากาศ, รสชาติ
บรรยากาศ, เฟอร์นิเจอร์, กาแฟ
กาแฟ, โรงคั่วกาแฟ, เค้กพาสชั่นฟรุ๊ต
ขนมจีน, ราคา, บรรยากาศ
อาหารไทย, กาแฟสด, บรรยากาศ
บรรยากาศ, เค้ก, มะนาวโซดา
ร้านกาแฟโบราณ, ชามะนาว, ราคาถูก
อาหารเช้า, ราคา, บุฟเฟต์
ชาบู, ไต้หวัน, อาหารหลากหลาย
บรรยากาศ, อาหาร, การบริการ
บริการ, กาแฟ, คุณภาพ
รสชาติ, กาแฟ, กลับมา
ร้านอาหาร, บรรยากาศ, กาแฟ
เฉาก๋วย, ชามะนาว, บริการรวดเร็ว
บรรยากาศ, กาแฟ, ราคา
อาหารญี่ปุ่น, สเต๊ก, ข้าวหน้าปลาดิบ
ร้านกาแฟ, ชาแอปเปิ้ล, บานนอฟฟี่
เพชรเกษม, ก๋วยเตี๋ยว, ต้มยำ
กาแฟ, ราคา, บรรยากาศ
butter, กรอบ, สตรอเบอร์รี่
กาแฟ, เอสเพรสโซ, บรรยากาศ
อาหารอิตาเลียน, พิซซ่า, บรรยากาศ
บรรยากาศ, หัวหิน, อาหาร
กาแฟ, ราคา, Jim thomson
ส้มตำ, บรรยากาศ, อาหาร
เค้ก, ขนมปัง, อาหารคาว
กาแฟ, โปรโมชั่น, ราคา
เซ็นทรัลพระราม 9, ร้านกาแฟ, ราคา
โดนัท, Samsung Galaxy, สตรอเบอรี่
ร้านสะดวกซื้อ, เครื่องดื่ม, สเต็ก
น้ำยา, ปลา, ก๋วยเตี๋ยว
น้ำผึ้ง, ฟาร์มผึ้ง, อาหาร
ติ่มซำ, ซาลาเปา, ข้าวต้มปลา
สเต็ก, ราคา, บรรยากาศ
กาแฟโบราณ, ร้านอาหาร, ขอนแก่น
กาแฟ, บรรยากาศ, ราคา
ร้าน, บรรยากาศ, พนักงาน
อาหาร, สด, ชีส
บรรยากาศ, คัพเค้ก, กาแฟ
Yakiniku, น้ำจิ้ม Ronin, อาหารทะเล
โมไอ, ราปานูอี, สโตนเฮน
รสชาติ, เค้ก, ไม่ถูกใจ
ร้านกาแฟ, บรรยากาศชิลล์, ราคา
กาแฟโบราณ, ราคา, รสชาติ
กาแฟ, บรรยากาศ, รสชาติดี
กาแฟ, บรรยากาศ, ราคา
หัวหิน, ปรานบุรี, Villa Gris
บุฟเฟต์, ไส้กรอก, ราคา
bakery, pastry, take away
กาแฟ, ราคา, friendly
อาหารคาว, โรตี, เค้ก
กาแฟ, เครป, บรรยากาศ
กาแฟ, บรรยากาศ, ราคา
food tasting, hand made, รายละเอียด
กาแฟ, อาหาร, พนักงาน
วาฟเฟิล, ราคา, บรรยากาศ
ขนมจีน, อ่างศิลา, รสชาติดี
คาเฟ่, สไตล์เรโทร, ฟิวชั่น
ขนม, ชา, มาการอง
กาแฟ, ราคา, ความสะอาด
บรรยากาศ, กาแฟ, ราคา
กาแฟ, รสชาติเข้มข้น, บรรยากาศ
ร้าน wilaiwan, กาแฟ illy, smoothie
บรรยากาศ, ราคา, มาการอง
ร้านกาแฟ, บรรยากาศน่ารัก, ราคาไม่แพง
กาแฟ, วาฟเฟิล, กาแฟร้อน
กาแฟ, บรรยากาศ, ชาเขียว
อาหาร, ราคา, ลูกค้า
ร้านกาแฟโบราณ, ตลาดเรือนโบราณ, กาแฟโบราณ
บรรยากาศ, กาแฟ, ราคา
ห้าง, บรรยากาศ, ราคา
ขนมสาลี, สุพรรณบุรี, ของฝาก
บรรยากาศ, ราคา, เค้ก
แหนมเนือง, ความสะอาด, กลิ่นอับ
ไอศกรีม, อาหาร, บรรยากาศ
อาหาร, ไทย, ฝรั่ง
ทูน่า, ไข่, สลัด
อาหารเวียดนาม, ไข่กะทะ, ราคา
สตาร์บัคส์, ระยอง, บริการ
เค้ก, โทสต์, ชาเขียว
กาแฟ, บรรยากาศ, เค้ก
บรรยากาศ, กาแฟ, ของฝาก
ข้าวหน้า, ราคา, รสชาติ
กาแฟ, เอสเพรสโซ่, บริการ
รสชาติ, เจ้าของ, คุณภาพ
บรรยากาศ, กาแฟ, ร้านอาหาร
กาแฟ, รสชาติ, ความทรงจำ
ร้านกาแฟ, บรรยากาศ, ต้นตีนตุ๊กแก
ร้าน, เบอร์เกอรี่, กาแฟ
บรรยากาศ, เค้ก, ราคา
โปรโมชั่น, เครื่องดื่ม, ฮันนี่โทส
แพนเค้ก, กล้วย, บรรยากาศ
กาแฟ, บรรยากาศ, บริการตัวเอง
บรรยากาศ, การบริการ, อาหารตามสั่ง
ชัยภูมิ, ห้องพัก, อาหาร
อาหาร, เค้ก, บรรยากาศ
กาแฟ, รสชาติ, คุณภาพ
กาแฟ, บรรยากาศ, รสชาติ
ก๋วยเตี๋ยว, ไม่ใส่ผงชูรส, ราคา
BTS, อโศก, ชาเย็น
บรรยากาศ, ราคา, เค้ก
ร้านกาแฟ, เค้ก, บรรยากาศ
เค้ก, อร่อย, นิมมาน
ร้านกาแฟ, บรรยากาศ, เมล็ดกาแฟ
สยามเซนเตอร์, มอคค่า, บรรยากาศ
กาแฟ, ราคา, อาหารหลากหลาย
เค้ก, บลูเบอร์รี่, ราคา
นิมมาน, ออมเล็ต, บรรยากาศ
บรรยากาศ, กาแฟ, ราคา
บรรยากาศ, กาแฟ, ราคา
ไอศกรีม, สุขภาพ, บอลโลก
ขนมปังปิ้ง, นมสด, ฮันนี่โทสต์
บรรยากาศ, กาแฟ, มุกดาหาร
กาแฟ, บรรยากาศ, พายหมูหยอง
กาแฟ, บรรยากาศ, ความเป็นมิตร
ขนมปัง, บรรยากาศ, ราคา
ร้านกาแฟ, พัทยา, ขนม
ร้านกาแฟ, บรรยากาศ, เค้ก

In [116]:
context_prompt = PromptTemplate(
    template="""จาก Review ต่อไปนี้
    Extract context ใน Review ที่เป็นตัวแทนที่บรรยายคำว่า {keyword} ได้ดีที่สุด

    Review: {review}

    ตอบผลลัพธ์ในรูปแบบ JSON โดยมีคีย์เป็น 'context'
    และค่าเป็นข้อความที่ดึงได้จาก Review

    ตัวอย่าง
    keyword คือ "กาแฟ"
    context: "กาแฟที่นี่อร่อยมาก หอมกลิ่นกาแฟคั่วสด"

    หากไม่พบข้อมูลให้ตอบ 'ไม่ระบุ'
    """
)

In [117]:
sentiment_prompt = PromptTemplate(
    template="""จากข้อความต่อไปนี้ ให้วิเคราะห์ว่าเป็น sentiment แบบไหน
    เลือกจากตัวเลือกเหล่านี้เท่านั้น: "positive", "negative", "neutral"

    ข้อความ: {message}

    ตอบในรูปแบบ JSON โดยมีคีย์เป็น 'sentiment'
    และค่าเป็นหนึ่งใน list ต่อไปนี้ [positive, negative, neutral]

    คำแนะนำ
    - positive คือ ข้อความที่แสดงความพอใจ ชอบ ดี
    - negative คือ ข้อความที่แสดงความไม่พอใจ ไม่ชอบ แย่
    - neutral คือ ข้อความที่ไม่แสดงความรู้สึกชัดเจน เป็นกลาง

    # ตัวอย่าง
    # ข้อความ "อร่อยมาก" → {{"sentiment": "positive"}}
    # ข้อความ "แพงไป" → {{"sentiment": "negative"}}
    # ข้อความ "ปกติ" → {{"sentiment": "neutral"}}
    """
)

In [118]:
class ContextKeyword(BaseModel):
    context: str = Field(..., description="context that best represent this keyword")

class ContexExtraction(BaseModel):
    extracted: ContextKeyword

context_parser = JsonOutputParser(pydantic_object=ContexExtraction)

In [119]:
context_extract = context_prompt | llm3 | context_parser

In [120]:
class Sentiment(BaseModel):
    sentiment: str = Field(..., description="sentiment of review")

class SentimentExtraction(BaseModel):
    extracted: Sentiment


sentiment_parser = JsonOutputParser(pydantic_object=SentimentExtraction)

In [121]:
sentiment_extract = sentiment_prompt | llm3 | sentiment_parser

In [122]:
results_1000[0]['text']['keywords'].split(',')

['ราคา', ' บรรยากาศ', ' ไข่ต้ม']

In [123]:
context_inputs = []

for review_data in tqdm(results_1000, desc="Preparing context inputs"):
    review = review_data['review']
    keywords = review_data['text']['keywords'].split(',')
    for keyword in keywords:
        context_inputs.append({"review": review, "keyword": keyword.strip()})

Preparing context inputs: 100%|██████████| 1000/1000 [00:00<00:00, 358702.13it/s]

In [124]:
len(context_inputs)

3000

In [125]:
context_results = []
for i in tqdm(range(len(results_1000)), desc="Extracting contexts"):
   result = context_extract.batch(context_inputs[i*3:(i*3)+3])
   contexts_list = [d['context'] for d in result]
   results_1000[i]['contexts'] = contexts_list

Extracting contexts: 100%|██████████| 1000/1000 [1:13:07<00:00,  4.39s/it]

In [126]:
results_1000[:5]

[{'review': 'ร้านอาหารใหญ่มากกกกกกก \nเลี้ยวเข้ามาเจอห้องน้ำก่อนเลย เออแปลกดี \nห้องทานหลักๆอยู่ชั้น 2 มีกาแฟ น้ำผึ้ง ซึ่งก็แค่เอาน้ำผึ้งมาราด แพงเวอร์ อย่าสั่งเลย \nลาบไข่ต้ม ไข่มันคาวอะ เลยไม่ประทับใจเท่าไหร่\nทอดมันหัวปลีกรอบอร่อยต้องเบิ้ล \nพะแนงห่อไข่อร่อยดี เห้ยแต่ราคา 150บาทมันเกินไปนะ รับไม่ไหวว\nเลิกกินแล้วมีขนมหวานให้กินฟรีเล็กน้อย )ขนมไทย) \n\nคงไม่ไปซ้ำ แพงเกิน ',
  'text': {'keywords': 'ราคา, บรรยากาศ, ไข่ต้ม'},
  'contexts': ['ราคา 150 บาทมันเกินไปนะ รับไม่ไหวว',
   'บรรยากาศร้านใหญ่มากกกกกกก',
   'ไข่ต้ม']},
 {'review': 'วันนี้ได้มีโอกาสไปนั่งซดกาแฟที่ร้านวาวี แถวๆอารีย์\n\nก็ได้ยินมาบ่อยๆละ จากหลายที่ แต่ที่บ่อยสุดก็จาก Twitter ว่ากาแฟที่นี่อร่อยมากกกกกกก\nเรียกว่าระดับแฟนๆ Starbuck ยังต้องเหลียวมามอง ก็ดองมานานจนถึงวันนี้โอกาสเหมาะ ไป\npresent งานที่ตึก Software Park เสร็จก็เลยมาหาไรกินแถวนี้พอดี\nจัดไป.....\n\n\nบรรยากาศรอบๆร้านก็แต่งได้น่านั่ง อารมณ์ประมาณว่าอยู่ในสวนบ้านเราเอง ต้นไม้เยอะดี\nอย่างน้อยก็เป็นสีเขียวเล็กๆ ในใจกลางเมืองได้ละ\nเขียวชอุ่ม\n\nว่าแล้วไม่รอช้าขอ Test ไม่สิ Taste เลยดีกว่าเดินเข้าร้านทันใด ป้าบบ...\n\n"พี่คับ เอา...ลาเต้ ร้อนแก้วนึงคับ"\nว่างๆ มานั่งจิบกาแฟ ฟังเพลง พักผ่อนได้ดีทีเดียว\n\nจ่ายตังเสร็จ ก็ถูกพนักงานอัญเชิญไปรอที่โต๊ะ 55+ เพราะที่นี่เขาเสริฟให้ถึงที่ หุๆ\nก็เลือกที่นั่งริมกระจก จะได้เห็นสาวๆ เอ้ย วิวถนัดๆหน่อย\nนั่งชมวิวรอกาแฟมา\n\nไม่นานเกินอึดใจ ไวไวยังไม่ทันสุก ลาเต้ร้อนๆก็มาวางอยู่ข้างหน้า\nซู้ดดดดดดด อ่าห์\n\nชำเลืองตามองลงไป....โอ้วว ที่นี่มีเล่นลายฟองนมด้วยเว้ยยย\nแต่พอดีด้วยความตะกละไปนิดดันฉีกน้ำตาลเทใส่แล้วเผลอคน ก็เลยไม่ได้\nถ่ายรูปมาให้ดู 55+ เหลือแต่ซากอารยธรรมลาเต้เมพๆ\n\n\nหน้าตาผ่าน ที่นี่ก็รสชาติ 1...2.....ชู้ดดดดดดด\nเฮ้ยยย นี่มัน....เมพพพพ ถึงเราจะไม่ค่อยรู้เรื่องกาแฟมากนัก แต่เท่าที่เคยลองชิมๆ\nมา รสชาติและกลิ่นมันไม่ธรรมดาเลย หอมๆ ถือว่าเป็นมวยรุ่นเดียวกะ Starbuck ได้\n\n\nเมนูอื่นๆ ลองชิม Coco ปั่น ของเพื่อนก็แหล่มไม่แพ้กัน วิปครีมหวานมัน โกโก้ก็หอม\nส่วนเพื่อนอีกคนสั่งน้ำส้มกะเค้กช็อกโกแลตมันก็บอกว่าแจ่ม ......\n\n\nสรุปก็คือ บรรยากาศก็ดี บริการก็ดี กาแฟอร่อย ราคาไม่แพง(แต่กินบ่อยก็จุกได้)\nถ้าครายผ่านแถวอารีย์มากินเหอะ ซอยไรจำไม่ได้รู้แต่อยู่ตรงข้าม Villa ตรง BS อารีย์เลยอะ 55+\n\nถ่ายโดย : Tan\nกล้อง : ซัมซวย Omnia i900 (สีภาพถึงได้ไม่ค่อยสวยเท่าไหร) ',
  'text': {'keywords': 'กาแฟ, บรรยากาศ, รสชาติ'},
  'contexts': ['กาแฟที่นี่อร่อยมากกกกกกก เรียกว่าระดับแฟนๆ Starbuck ยังต้องเหลียวมามอง',
   'บรรยากาศรอบๆร้านก็แต่งได้น่านั่ง อารมณ์ประมาณว่าอยู่ในสวนบ้านเราเอง ต้นไม้เยอะดี อย่างน้อยก็เป็นสีเขียวเล็กๆ ในใจกลางเมืองได้ละ เขียวชอุ่ม',
   'รสชาติและกลิ่นมันไม่ธรรมดาเลย หอมๆ ถือว่าเป็นมวยรุ่นเดียวกะ Starbuck ได้']},
 {'review': 'สารภาพว่าไม่เคยคิดจะไปต่อคิวซื้อมากินเองครับ บังเอิญมีรุ่นน้องที่ไม่ได้เจอกันนานชวนไปเป็นเพื่อน แล้วเค้าให้ซื้อได้คนละกล่อง เลยเข้าไปต่อคิวซื้อให้น้องเพิ่มอีกกล่องนึง น้องใจดีแบ่งมาให้ชิมหนึ่งชิ้นถ้วน ^^"\n\nรออยู่เกือบสองชั่วโมง ได้ลัดคิวเพราะสั่ง original แบบ glazed ทั้งกล่อง หลังร้านจะมีที่นั่งนะครับ เป็นโต๊ะเก้าอี้ แต่ไม่ค่อยมีคนนั่งซักเท่าไหร่ ก็สะดวกดีสำหรับการนัดพบกัน (ถ้าร้านยังอยู่ต่อไปนะ ^^)\n\nมาถึงตัวโดนัท เสียดายที่ใส่กล่องทิ้งไว้นานแล้วเลยไม่ค่อยอุ่น ถ้าเสร็จใหม่ๆหรือเอาไปอบเพิ่มน่าจะดีกว่านี้ เนื้อแป้งนิ่มมากถ้าเทียบกับยี่ห้อใกล้เคียงที่เป็นแบบเดียวกัน ทำให้เวลาจับเบาๆน้ำตาลก็จะร่วงออกมาง่ายไปหน่อย\n\nน้องบอกว่าหวานไป ผมเห็นด้วยส่วนนึง เพราะแป้งนิ่มเวลากินก็จะทำให้รับรสหวานจากแป้งได้ง่ายกว่า ยิ่งทำให้น้ำตาลที่เคลือบอยู่แบบไม่หนา ซึ่งหวานพอดีอยู่แล้วดันหวานขึ้นไปอีก แต่ถ้ากินพร้อมกาแฟน่าจะเวิร์กครับ\n\nก็หวังว่าจะอยู่ต่อไปนานๆ อย่าโรยราไปตามความนิยมที่ยังไงๆ ก็ต้องลดลงตามเวลา่นะครับ :D',
  'text': {'keywords': 'โดนัท, น้ำตาล, รสชาติ'},
  'contexts': ['เนื้อแป้งนิ่มมากถ้าเทียบกับยี่ห้อใกล้เคียงที่เป็นแบบเดียวกัน ทำให้เวลาจับเบาๆน้ำตาลก็จะร่วงออกมาง่ายไปหน่อย',
   'น้ำตาลที่เคลือบอยู่แบบไม่หนา ซึ่งหวานพอดีอยู่แล้วดันหวานขึ้นไปอีก',
   'เนื้อแป้งนิ่มมากถ้าเทียบกับยี่ห้อใกล้เคียงที่เป็นแบบเดียวกัน ทำให้เวลาจับเบาๆน้ำตาลก็จะร่วงออกมาง่ายไปหน่อย']},
 {'review': 'ร้านอาหารญี่ปุ่นร้านนี้ ใจจริงไม่อยากแนะนำเลยค่ะ อยากเก็บไว้เป็นความลับคนเดียว เพราะไม่อยากให้คนมาแย่งกินเลย ร้านนี้ดิชั้นยกให้เป็น "Best value Japanese set lunch in Thonglor" รู้จักมาได้เพราะจับได้ว่าส๊ามีชอบแอบไปกินอยู่คนเดียว พอถามเค้าว่าทำไมต้องไปกินคนเดียวด้วย เค้าก็บอกว่าอาหารที่นี่เป็นอาหารแห่งจิตวิิญญาณของเค้า เค้าอยากจะซึมซับมันเงียบๆ คนเดียว ดิชั้นเข้าใจเค้าค่ะ เพราะจำได้ว่าตอนที่เค้าพาดิชั้นกับลูกวัยซนไปกินครั้งแรก วิบัติมาก \n\nเข้าเรื่องดีกว่า จะดุูว่าร้านญี่ปุ่นร้านไหนอร่อย และที่สำคัญคุ้มค่า ในย่านทองหล่อนะคะ ให้ดูว่ามื้อกลางวันแม่บ้านญี่ปุ่นเค้าไปทานกันที่ไหน วาซาบิอันเป็นหนึ่งในร้านที่แม่บ้านญี่ปุ่นนิยมทานกัน สาเหตุก็เพราะคุณภาพอาหารและราคาที่ยากจะหาใครสู้ค่ะ วันนี้สั่งอาหารชุดปลาซาบะย่าง (300 บาท) มีให้เลือกว่าจะย่างเกลือหรือย่างซีอิ๊ว แค่ได้เห็นปลาที่ยกมาเสิร์ฟก็คุ้มค่าแล้วค่ะ เพราะร้านอื่นๆ รูปปลาในเมนูมักจะดูชิ้นใหญ่กว่าที่เสิร์ฟ แต่ร้านนี้ปลาที่ได้ชิ้นใหญ่กว่าที่เห็นในเมนูมาก ขนาดเท่าฝ่ามือเลยค่ะ ปลาซาบะย่างเกลือทานกับหัวไขเท้าฝนและบีบมะนาวนิดหน่อย เนื้อปลาหวานนุ่มชุ่มน้ำมันปลา กินกับข้าวญ่ีปุ่นร้อนๆ อร่อยอย่าบอกใคร แทบจะลืมเครื่องเคียงที่เอาไว้แกล้ม มีทั้งหน่อไม้คลุกปลาแห้ง แตงกวาดอง ซุปมิโซะ และไข่ตุ่๋น  ไข่ตุ่๋นที่นี่เน้ือเนียนนุ่ม ตักเข้าปากแล้ว melt in your mouth ทันที รสชาดก็เริ่ด เพราะเค้าใช้น้ำซุปอย่างดีมาทำค่ะ พอทานไปแป๊บนึงเค้าก็จะยกปลาดิบที่แถมมากับเซ็ต ซึ่งมีปลาโอ 2 ชิ้นเบิ้ม และปลาหมึกอีก 2 ชิ้น โอวสุดคุ้ม\n\nส่วนส๊ามีสั่ง Tekkadon Set (ข้าวหน้าปลาทูน่าเนื้อแดง 340 บาท) เชฟบอกว่าปลาทูน่าเพิ่งส่งมาจากญี่ปุ่นเลยค่ะ ปลาทูน่าชิ้นใหญ่ 8 ชิ้นวางลงบนข้าวคลุกน้ำส้มสายชู คัมเปียว เห็ดหอมหมักซีอิ๊ว รสชาดกลมกล่อม เอาวาซาบิสดๆ แต้มบนเนื้อปลานิดนึง เสร็จแล้วเอาโชยุราดทับ ฮีอม ในเซ็ตยังมีไข่ตุ่นและอุด้ง ซึ่งมีให้เลือกทั้งร้อนและเย็น วันนี้เราสั่งแบบร้อน ซุปเค้ารสชาดดีมาก ส๊ามีบอกว่า ชิราชิเซ็ต (ข้าวหน้าปลาดิบรวม) ของร้านนี้ก็คุ้มสุดยอด \n\nทานเสร็จยังมีชากาแฟ ร้อนหรือเย็น เสิร์ฟพร้อมขนมโมจิ และถั่วแดงเย็นปิดท้าย เห็นมั๊ยล่ะคะ คุ้มค่าขนาดนี้แม่บ้านญี่ปุ่นถึงได้มา "โออิชิ โออิชิ" กันทุกกลางวัน ตอนจ่ายเงินก็ไม่หงุดหงิด เพราะราคาในเมนูคือราคาที่เน็ตแล้ว ไม่มี VAT หรือ Service charge มาบวกเพิ่มให้กวนใจ\n\nวาซาบิอันตั้งอยู่ที่ต้นซอยทองหล่อฝั่งสุขุมวิท ตรงทางเข้า Grand Tower จอดรถได้ในลานจอดของ Grand Tower แล้วนำบัตรมาประทับตราที่ร้านค่ะ',
  'text': {'keywords': 'ปลาซาบะ, ไข่ตุ๋น, ราคาคุ้มค่า'},
  'contexts': ['วันนี้สั่งอาหารชุดปลาซาบะย่าง (300 บาท) มีให้เลือกว่าจะย่างเกลือหรือย่างซีอิ๊ว แค่ได้เห็นปลาที่ยกมาเสิร์ฟก็คุ้มค่าแล้วค่ะ เพราะร้านอื่นๆ รูปปลาในเมนูมักจะดูชิ้นใหญ่กว่าที่เสิร์ฟ แต่ร้านนี้ปลาที่ได้ชิ้นใหญ่กว่าที่เห็นในเมนูมาก ขนาดเท่าฝ่ามือเลยค่ะ ปลาซาบะย่างเกลือทานกับหัวไขเท้าฝนและบีบมะนาวนิดหน่อย เนื้อปลาหวานนุ่มชุ่มน้ำมันปลา กินกับข้าวญี่ปุ่นร้อนๆ อร่อยอย่าบอกใคร',
   'ไข่ตุ๋นที่นี่เน้ือเนียนนุ่ม ตักเข้าปากแล้ว melt in your mouth ทันที รสชาดก็เริ่ด เพราะเค้าใช้น้ำซุปอย่างดีมาทำค่ะ',
   'วาซาบิอันตั้งอยู่ที่ต้นซอยทองหล่อฝั่งสุขุมวิท ตรงทางเข้า Grand Tower จอดรถได้ในลานจอดของ Grand Tower แล้วนำบัตรมาประทับตราที่ร้านค่ะ']},
 {'review': 'เดือนแรกที่เค้าต่อคิวกัน 2 - 3 ชั่วโมง เราก็ว่าเค้าบ้าอ่ะ...เมืองนอกเมืองนาเค้าแจกฟรีให้ชิมในขณะที่ทำ Original Glazed สดๆ ... แล้ววันนึงอ้อมที่อ้อมเบื่อ(งาน)ถึงขีดสุด ก็ไปลองต่อแถวมั่ง ฮ่าๆๆ บ้าดีเนอะ ต่อไปก็แอบฟังคนข้างๆคุยกัน...ส่วนมากจะเป็นแบบว่า แฟนสาว "เธอว์...เพื่อนเค้าบอกว่าอร่อยแบบละลายในปากเลยนะ อยากกิวอ่าอยากกิว"...แฟนหนุ่ม (คิดในใจ ถ้าพูดออกมาเดี๋ยวมีงอน)"บ้าป่าวอ่ะ ต่อไรนาน วู้ววว" ต่อคิว 2 ชั่วโมงครึ่งค่ะ พอซื้อได้เหมือนมีชัยชนะ โดนัทอร่อยขึ้นมาอย่างไม่น่าเชื่อ แต่อ้อมซื้อแล้วก็แจกคนไปทั่วนะคะ กินแค่ 2 ชิ้นพอ แบ่งปันความสุขให้คนอื่น มีความสุขอีกสิบเท่าค่ะ\n\nเข้าเรื่อง!! KK นี่กินมาหลายสาขาก่อนเปิดที่ไทย ขอบอกว่า KK ไทย ไม่ทำให้ผิดหวัง Original glazed รสชาติเหมือนกันเรย :) นิ่มสยิวกิ้ววว >_<" ถ้าจะให้ดีต้องกินแบบใหม่ๆเลยนะคะ แป้งจะนุ่ม น้ำตาลจะกรอบและไม่หวานเกินไป เรียกได้ว่าเป็นสุดยอดโดนัทจริงๆ กินยังไงก็ยังอร่อยค่ะ แต่ถ้าปล่อยข้ามวันแล้ว ถึงแม้จะเอามาเวฟ 8 วิ ก็จะรู้สึกว่าหวานไปนิส ขอแนะนำให้กินกะกาแฟค่ะ หวานนิสตัดกะขมหน่อย อร่ออยเหาะเลยค่ะ\n\nรสชาติอื่นยังไม่เคยลองสาขานี้นะคะ แต่ยังไงอ้อมว่า Original glazed ก็ฟินสุดละค่ะ ยอมรับว่าอาจจะไม่คุ้มกับการต่อคิว 2 ชั่วโมง แต่ตอนนี้คิวแค่ 10 นาที (ฝั่งติดกระจกเป็นแบบเลือกหลายรส ถ้าฝั่งด้านนอกเป็นแถว Original glazed เท่านั้น) ขอบอกว่าคุ้มอย่างแน่นอนนะคะ ขอติดให้ห้าตาวค่ะ ด้วยความที่เป็นสาวกมานาน\n\nปล.ตอนอ้อมซื้อ Citibank ซื้อ 12 ชิ้น (รสใดก็ได้) ได้ฟรี 6 ชิ้น Original glazed ค่ะ',
  'text': {'keywords': 'โดนัท, Original Glazed, คิว'},
  'contexts': ['Original Glazed รสชาติเหมือนกันเรย',
   'Original Glazed รสชาติเหมือนกันเรย',
   'ต่อคิว 2 ชั่วโมงครึ่งค่ะ พอซื้อได้เหมือนมีชัยชนะ']}]

In [127]:
sentiment_inputs = []

for review_data in tqdm(results_1000, desc="Preparing sentiment inputs"):
    contexts = review_data['contexts']
    for context in contexts:
        sentiment_inputs.append({"message": context})

Preparing sentiment inputs: 100%|██████████| 1000/1000 [00:00<00:00, 288426.90it/s]

In [128]:
len(sentiment_inputs)

3000

In [129]:
sentiment_inputs[:6]

[{'message': 'ราคา 150 บาทมันเกินไปนะ รับไม่ไหวว'},
 {'message': 'บรรยากาศร้านใหญ่มากกกกกกก'},
 {'message': 'ไข่ต้ม'},
 {'message': 'กาแฟที่นี่อร่อยมากกกกกกก เรียกว่าระดับแฟนๆ Starbuck ยังต้องเหลียวมามอง'},
 {'message': 'บรรยากาศรอบๆร้านก็แต่งได้น่านั่ง อารมณ์ประมาณว่าอยู่ในสวนบ้านเราเอง ต้นไม้เยอะดี อย่างน้อยก็เป็นสีเขียวเล็กๆ ในใจกลางเมืองได้ละ เขียวชอุ่ม'},
 {'message': 'รสชาติและกลิ่นมันไม่ธรรมดาเลย หอมๆ ถือว่าเป็นมวยรุ่นเดียวกะ Starbuck ได้'}]

In [130]:
for i in tqdm(range(len(results_1000)), desc="Extracting sentiment"):
   result = sentiment_extract.batch(sentiment_inputs[i*3:(i*3)+3])
   sentiment_list = [d['sentiment'] for d in result]
   results_1000[i]['sentiment'] = sentiment_list

Extracting sentiment: 100%|██████████| 1000/1000 [44:11<00:00,  2.65s/it]

In [131]:
results_1000[0:5]

[{'review': 'ร้านอาหารใหญ่มากกกกกกก \nเลี้ยวเข้ามาเจอห้องน้ำก่อนเลย เออแปลกดี \nห้องทานหลักๆอยู่ชั้น 2 มีกาแฟ น้ำผึ้ง ซึ่งก็แค่เอาน้ำผึ้งมาราด แพงเวอร์ อย่าสั่งเลย \nลาบไข่ต้ม ไข่มันคาวอะ เลยไม่ประทับใจเท่าไหร่\nทอดมันหัวปลีกรอบอร่อยต้องเบิ้ล \nพะแนงห่อไข่อร่อยดี เห้ยแต่ราคา 150บาทมันเกินไปนะ รับไม่ไหวว\nเลิกกินแล้วมีขนมหวานให้กินฟรีเล็กน้อย )ขนมไทย) \n\nคงไม่ไปซ้ำ แพงเกิน ',
  'text': {'keywords': 'ราคา, บรรยากาศ, ไข่ต้ม'},
  'contexts': ['ราคา 150 บาทมันเกินไปนะ รับไม่ไหวว',
   'บรรยากาศร้านใหญ่มากกกกกกก',
   'ไข่ต้ม'],
  'sentiment': ['negative', 'positive', 'neutral']},
 {'review': 'วันนี้ได้มีโอกาสไปนั่งซดกาแฟที่ร้านวาวี แถวๆอารีย์\n\nก็ได้ยินมาบ่อยๆละ จากหลายที่ แต่ที่บ่อยสุดก็จาก Twitter ว่ากาแฟที่นี่อร่อยมากกกกกกก\nเรียกว่าระดับแฟนๆ Starbuck ยังต้องเหลียวมามอง ก็ดองมานานจนถึงวันนี้โอกาสเหมาะ ไป\npresent งานที่ตึก Software Park เสร็จก็เลยมาหาไรกินแถวนี้พอดี\nจัดไป.....\n\n\nบรรยากาศรอบๆร้านก็แต่งได้น่านั่ง อารมณ์ประมาณว่าอยู่ในสวนบ้านเราเอง ต้นไม้เยอะดี\nอย่างน้อยก็เป็นสีเขียวเล็กๆ ในใจกลางเมืองได้ละ\nเขียวชอุ่ม\n\nว่าแล้วไม่รอช้าขอ Test ไม่สิ Taste เลยดีกว่าเดินเข้าร้านทันใด ป้าบบ...\n\n"พี่คับ เอา...ลาเต้ ร้อนแก้วนึงคับ"\nว่างๆ มานั่งจิบกาแฟ ฟังเพลง พักผ่อนได้ดีทีเดียว\n\nจ่ายตังเสร็จ ก็ถูกพนักงานอัญเชิญไปรอที่โต๊ะ 55+ เพราะที่นี่เขาเสริฟให้ถึงที่ หุๆ\nก็เลือกที่นั่งริมกระจก จะได้เห็นสาวๆ เอ้ย วิวถนัดๆหน่อย\nนั่งชมวิวรอกาแฟมา\n\nไม่นานเกินอึดใจ ไวไวยังไม่ทันสุก ลาเต้ร้อนๆก็มาวางอยู่ข้างหน้า\nซู้ดดดดดดด อ่าห์\n\nชำเลืองตามองลงไป....โอ้วว ที่นี่มีเล่นลายฟองนมด้วยเว้ยยย\nแต่พอดีด้วยความตะกละไปนิดดันฉีกน้ำตาลเทใส่แล้วเผลอคน ก็เลยไม่ได้\nถ่ายรูปมาให้ดู 55+ เหลือแต่ซากอารยธรรมลาเต้เมพๆ\n\n\nหน้าตาผ่าน ที่นี่ก็รสชาติ 1...2.....ชู้ดดดดดดด\nเฮ้ยยย นี่มัน....เมพพพพ ถึงเราจะไม่ค่อยรู้เรื่องกาแฟมากนัก แต่เท่าที่เคยลองชิมๆ\nมา รสชาติและกลิ่นมันไม่ธรรมดาเลย หอมๆ ถือว่าเป็นมวยรุ่นเดียวกะ Starbuck ได้\n\n\nเมนูอื่นๆ ลองชิม Coco ปั่น ของเพื่อนก็แหล่มไม่แพ้กัน วิปครีมหวานมัน โกโก้ก็หอม\nส่วนเพื่อนอีกคนสั่งน้ำส้มกะเค้กช็อกโกแลตมันก็บอกว่าแจ่ม ......\n\n\nสรุปก็คือ บรรยากาศก็ดี บริการก็ดี กาแฟอร่อย ราคาไม่แพง(แต่กินบ่อยก็จุกได้)\nถ้าครายผ่านแถวอารีย์มากินเหอะ ซอยไรจำไม่ได้รู้แต่อยู่ตรงข้าม Villa ตรง BS อารีย์เลยอะ 55+\n\nถ่ายโดย : Tan\nกล้อง : ซัมซวย Omnia i900 (สีภาพถึงได้ไม่ค่อยสวยเท่าไหร) ',
  'text': {'keywords': 'กาแฟ, บรรยากาศ, รสชาติ'},
  'contexts': ['กาแฟที่นี่อร่อยมากกกกกกก เรียกว่าระดับแฟนๆ Starbuck ยังต้องเหลียวมามอง',
   'บรรยากาศรอบๆร้านก็แต่งได้น่านั่ง อารมณ์ประมาณว่าอยู่ในสวนบ้านเราเอง ต้นไม้เยอะดี อย่างน้อยก็เป็นสีเขียวเล็กๆ ในใจกลางเมืองได้ละ เขียวชอุ่ม',
   'รสชาติและกลิ่นมันไม่ธรรมดาเลย หอมๆ ถือว่าเป็นมวยรุ่นเดียวกะ Starbuck ได้'],
  'sentiment': ['positive', 'positive', 'positive']},
 {'review': 'สารภาพว่าไม่เคยคิดจะไปต่อคิวซื้อมากินเองครับ บังเอิญมีรุ่นน้องที่ไม่ได้เจอกันนานชวนไปเป็นเพื่อน แล้วเค้าให้ซื้อได้คนละกล่อง เลยเข้าไปต่อคิวซื้อให้น้องเพิ่มอีกกล่องนึง น้องใจดีแบ่งมาให้ชิมหนึ่งชิ้นถ้วน ^^"\n\nรออยู่เกือบสองชั่วโมง ได้ลัดคิวเพราะสั่ง original แบบ glazed ทั้งกล่อง หลังร้านจะมีที่นั่งนะครับ เป็นโต๊ะเก้าอี้ แต่ไม่ค่อยมีคนนั่งซักเท่าไหร่ ก็สะดวกดีสำหรับการนัดพบกัน (ถ้าร้านยังอยู่ต่อไปนะ ^^)\n\nมาถึงตัวโดนัท เสียดายที่ใส่กล่องทิ้งไว้นานแล้วเลยไม่ค่อยอุ่น ถ้าเสร็จใหม่ๆหรือเอาไปอบเพิ่มน่าจะดีกว่านี้ เนื้อแป้งนิ่มมากถ้าเทียบกับยี่ห้อใกล้เคียงที่เป็นแบบเดียวกัน ทำให้เวลาจับเบาๆน้ำตาลก็จะร่วงออกมาง่ายไปหน่อย\n\nน้องบอกว่าหวานไป ผมเห็นด้วยส่วนนึง เพราะแป้งนิ่มเวลากินก็จะทำให้รับรสหวานจากแป้งได้ง่ายกว่า ยิ่งทำให้น้ำตาลที่เคลือบอยู่แบบไม่หนา ซึ่งหวานพอดีอยู่แล้วดันหวานขึ้นไปอีก แต่ถ้ากินพร้อมกาแฟน่าจะเวิร์กครับ\n\nก็หวังว่าจะอยู่ต่อไปนานๆ อย่าโรยราไปตามความนิยมที่ยังไงๆ ก็ต้องลดลงตามเวลา่นะครับ :D',
  'text': {'keywords': 'โดนัท, น้ำตาล, รสชาติ'},
  'contexts': ['เนื้อแป้งนิ่มมากถ้าเทียบกับยี่ห้อใกล้เคียงที่เป็นแบบเดียวกัน ทำให้เวลาจับเบาๆน้ำตาลก็จะร่วงออกมาง่ายไปหน่อย',
   'น้ำตาลที่เคลือบอยู่แบบไม่หนา ซึ่งหวานพอดีอยู่แล้วดันหวานขึ้นไปอีก',
   'เนื้อแป้งนิ่มมากถ้าเทียบกับยี่ห้อใกล้เคียงที่เป็นแบบเดียวกัน ทำให้เวลาจับเบาๆน้ำตาลก็จะร่วงออกมาง่ายไปหน่อย'],
  'sentiment': ['negative', 'negative', 'negative']},
 {'review': 'ร้านอาหารญี่ปุ่นร้านนี้ ใจจริงไม่อยากแนะนำเลยค่ะ อยากเก็บไว้เป็นความลับคนเดียว เพราะไม่อยากให้คนมาแย่งกินเลย ร้านนี้ดิชั้นยกให้เป็น "Best value Japanese set lunch in Thonglor" รู้จักมาได้เพราะจับได้ว่าส๊ามีชอบแอบไปกินอยู่คนเดียว พอถามเค้าว่าทำไมต้องไปกินคนเดียวด้วย เค้าก็บอกว่าอาหารที่นี่เป็นอาหารแห่งจิตวิิญญาณของเค้า เค้าอยากจะซึมซับมันเงียบๆ คนเดียว ดิชั้นเข้าใจเค้าค่ะ เพราะจำได้ว่าตอนที่เค้าพาดิชั้นกับลูกวัยซนไปกินครั้งแรก วิบัติมาก \n\nเข้าเรื่องดีกว่า จะดุูว่าร้านญี่ปุ่นร้านไหนอร่อย และที่สำคัญคุ้มค่า ในย่านทองหล่อนะคะ ให้ดูว่ามื้อกลางวันแม่บ้านญี่ปุ่นเค้าไปทานกันที่ไหน วาซาบิอันเป็นหนึ่งในร้านที่แม่บ้านญี่ปุ่นนิยมทานกัน สาเหตุก็เพราะคุณภาพอาหารและราคาที่ยากจะหาใครสู้ค่ะ วันนี้สั่งอาหารชุดปลาซาบะย่าง (300 บาท) มีให้เลือกว่าจะย่างเกลือหรือย่างซีอิ๊ว แค่ได้เห็นปลาที่ยกมาเสิร์ฟก็คุ้มค่าแล้วค่ะ เพราะร้านอื่นๆ รูปปลาในเมนูมักจะดูชิ้นใหญ่กว่าที่เสิร์ฟ แต่ร้านนี้ปลาที่ได้ชิ้นใหญ่กว่าที่เห็นในเมนูมาก ขนาดเท่าฝ่ามือเลยค่ะ ปลาซาบะย่างเกลือทานกับหัวไขเท้าฝนและบีบมะนาวนิดหน่อย เนื้อปลาหวานนุ่มชุ่มน้ำมันปลา กินกับข้าวญ่ีปุ่นร้อนๆ อร่อยอย่าบอกใคร แทบจะลืมเครื่องเคียงที่เอาไว้แกล้ม มีทั้งหน่อไม้คลุกปลาแห้ง แตงกวาดอง ซุปมิโซะ และไข่ตุ่๋น  ไข่ตุ่๋นที่นี่เน้ือเนียนนุ่ม ตักเข้าปากแล้ว melt in your mouth ทันที รสชาดก็เริ่ด เพราะเค้าใช้น้ำซุปอย่างดีมาทำค่ะ พอทานไปแป๊บนึงเค้าก็จะยกปลาดิบที่แถมมากับเซ็ต ซึ่งมีปลาโอ 2 ชิ้นเบิ้ม และปลาหมึกอีก 2 ชิ้น โอวสุดคุ้ม\n\nส่วนส๊ามีสั่ง Tekkadon Set (ข้าวหน้าปลาทูน่าเนื้อแดง 340 บาท) เชฟบอกว่าปลาทูน่าเพิ่งส่งมาจากญี่ปุ่นเลยค่ะ ปลาทูน่าชิ้นใหญ่ 8 ชิ้นวางลงบนข้าวคลุกน้ำส้มสายชู คัมเปียว เห็ดหอมหมักซีอิ๊ว รสชาดกลมกล่อม เอาวาซาบิสดๆ แต้มบนเนื้อปลานิดนึง เสร็จแล้วเอาโชยุราดทับ ฮีอม ในเซ็ตยังมีไข่ตุ่นและอุด้ง ซึ่งมีให้เลือกทั้งร้อนและเย็น วันนี้เราสั่งแบบร้อน ซุปเค้ารสชาดดีมาก ส๊ามีบอกว่า ชิราชิเซ็ต (ข้าวหน้าปลาดิบรวม) ของร้านนี้ก็คุ้มสุดยอด \n\nทานเสร็จยังมีชากาแฟ ร้อนหรือเย็น เสิร์ฟพร้อมขนมโมจิ และถั่วแดงเย็นปิดท้าย เห็นมั๊ยล่ะคะ คุ้มค่าขนาดนี้แม่บ้านญี่ปุ่นถึงได้มา "โออิชิ โออิชิ" กันทุกกลางวัน ตอนจ่ายเงินก็ไม่หงุดหงิด เพราะราคาในเมนูคือราคาที่เน็ตแล้ว ไม่มี VAT หรือ Service charge มาบวกเพิ่มให้กวนใจ\n\nวาซาบิอันตั้งอยู่ที่ต้นซอยทองหล่อฝั่งสุขุมวิท ตรงทางเข้า Grand Tower จอดรถได้ในลานจอดของ Grand Tower แล้วนำบัตรมาประทับตราที่ร้านค่ะ',
  'text': {'keywords': 'ปลาซาบะ, ไข่ตุ๋น, ราคาคุ้มค่า'},
  'contexts': ['วันนี้สั่งอาหารชุดปลาซาบะย่าง (300 บาท) มีให้เลือกว่าจะย่างเกลือหรือย่างซีอิ๊ว แค่ได้เห็นปลาที่ยกมาเสิร์ฟก็คุ้มค่าแล้วค่ะ เพราะร้านอื่นๆ รูปปลาในเมนูมักจะดูชิ้นใหญ่กว่าที่เสิร์ฟ แต่ร้านนี้ปลาที่ได้ชิ้นใหญ่กว่าที่เห็นในเมนูมาก ขนาดเท่าฝ่ามือเลยค่ะ ปลาซาบะย่างเกลือทานกับหัวไขเท้าฝนและบีบมะนาวนิดหน่อย เนื้อปลาหวานนุ่มชุ่มน้ำมันปลา กินกับข้าวญี่ปุ่นร้อนๆ อร่อยอย่าบอกใคร',
   'ไข่ตุ๋นที่นี่เน้ือเนียนนุ่ม ตักเข้าปากแล้ว melt in your mouth ทันที รสชาดก็เริ่ด เพราะเค้าใช้น้ำซุปอย่างดีมาทำค่ะ',
   'วาซาบิอันตั้งอยู่ที่ต้นซอยทองหล่อฝั่งสุขุมวิท ตรงทางเข้า Grand Tower จอดรถได้ในลานจอดของ Grand Tower แล้วนำบัตรมาประทับตราที่ร้านค่ะ'],
  'sentiment': ['positive', 'positive', 'neutral']},
 {'review': 'เดือนแรกที่เค้าต่อคิวกัน 2 - 3 ชั่วโมง เราก็ว่าเค้าบ้าอ่ะ...เมืองนอกเมืองนาเค้าแจกฟรีให้ชิมในขณะที่ทำ Original Glazed สดๆ ... แล้ววันนึงอ้อมที่อ้อมเบื่อ(งาน)ถึงขีดสุด ก็ไปลองต่อแถวมั่ง ฮ่าๆๆ บ้าดีเนอะ ต่อไปก็แอบฟังคนข้างๆคุยกัน...ส่วนมากจะเป็นแบบว่า แฟนสาว "เธอว์...เพื่อนเค้าบอกว่าอร่อยแบบละลายในปากเลยนะ อยากกิวอ่าอยากกิว"...แฟนหนุ่ม (คิดในใจ ถ้าพูดออกมาเดี๋ยวมีงอน)"บ้าป่าวอ่ะ ต่อไรนาน วู้ววว" ต่อคิว 2 ชั่วโมงครึ่งค่ะ พอซื้อได้เหมือนมีชัยชนะ โดนัทอร่อยขึ้นมาอย่างไม่น่าเชื่อ แต่อ้อมซื้อแล้วก็แจกคนไปทั่วนะคะ กินแค่ 2 ชิ้นพอ แบ่งปันความสุขให้คนอื่น มีความสุขอีกสิบเท่าค่ะ\n\nเข้าเรื่อง!! KK นี่กินมาหลายสาขาก่อนเปิดที่ไทย ขอบอกว่า KK ไทย ไม่ทำให้ผิดหวัง Original glazed รสชาติเหมือนกันเรย :) นิ่มสยิวกิ้ววว >_<" ถ้าจะให้ดีต้องกินแบบใหม่ๆเลยนะคะ แป้งจะนุ่ม น้ำตาลจะกรอบและไม่หวานเกินไป เรียกได้ว่าเป็นสุดยอดโดนัทจริงๆ กินยังไงก็ยังอร่อยค่ะ แต่ถ้าปล่อยข้ามวันแล้ว ถึงแม้จะเอามาเวฟ 8 วิ ก็จะรู้สึกว่าหวานไปนิส ขอแนะนำให้กินกะกาแฟค่ะ หวานนิสตัดกะขมหน่อย อร่ออยเหาะเลยค่ะ\n\nรสชาติอื่นยังไม่เคยลองสาขานี้นะคะ แต่ยังไงอ้อมว่า Original glazed ก็ฟินสุดละค่ะ ยอมรับว่าอาจจะไม่คุ้มกับการต่อคิว 2 ชั่วโมง แต่ตอนนี้คิวแค่ 10 นาที (ฝั่งติดกระจกเป็นแบบเลือกหลายรส ถ้าฝั่งด้านนอกเป็นแถว Original glazed เท่านั้น) ขอบอกว่าคุ้มอย่างแน่นอนนะคะ ขอติดให้ห้าตาวค่ะ ด้วยความที่เป็นสาวกมานาน\n\nปล.ตอนอ้อมซื้อ Citibank ซื้อ 12 ชิ้น (รสใดก็ได้) ได้ฟรี 6 ชิ้น Original glazed ค่ะ',
  'text': {'keywords': 'โดนัท, Original Glazed, คิว'},
  'contexts': ['Original Glazed รสชาติเหมือนกันเรย',
   'Original Glazed รสชาติเหมือนกันเรย',
   'ต่อคิว 2 ชั่วโมงครึ่งค่ะ พอซื้อได้เหมือนมีชัยชนะ'],
  'sentiment': ['neutral', 'neutral', 'positive']}]

In [132]:
import pandas as pd

df = pd.DataFrame([
    {
        'review': r['review'],
        **{f'keyword{i+1}': k.strip() for i, k in enumerate(r['text']['keywords'].split(','))},
        **{f'context{i+1}_keyword': c for i, c in enumerate(r['contexts'])},
        **{f'sentiment{i+1}': s for i, s in enumerate(r['sentiment'])}
    }
    for r in results_1000
])

In [133]:
df.to_csv('results.csv', index=False, encoding='utf-8-sig')